SELECT USER
FROM DUAL;
--==>>TEAM4

--------------------------------------------------------------------------------
/*
CREATE TABLE STUDENT_REGISTER
(STUDENT_CODE    VARCHAR2(10)
,ID              VARCHAR2(20)
,PASSWORD        VARCHAR2(30) 
,NAME            VARCHAR2(20)
,SSN             VARCHAR2(13)
,REGISTER_DATE   DATE DEFAULT SYSDATE
,CONSTRAINT STD_CODE_PK PRIMARY KEY(STUDENT_CODE)        
);
*/
/*
1.MANAGER_REGISTER(관리자등록) → MA
MANAGER_CODE(관리자코드)    VARCHAR2(10)
PK: MA_CODE_PK(맨뒤 단어)

2.TEACHER_REGISTER(교수등록)→ TC
*/
--○ 관리자등록 테이블 생성
CREATE TABLE MANAGER_REGISTER
(MANAGER_CODE   VARCHAR2(10)           -- (관리자코드)
,ID             VARCHAR2(10)           -- (ID)
,PASSWORD       VARCHAR2(30)           -- (비밀번호)
,REGISTER_DATE  DATE DEFAULT SYSDATE   -- (관리자 등록일자)
,CONSTRAINT MA_CODE_PK PRIMARY KEY(MANAGER_CODE)
,CONSTRAINT MA_ID_NN CHECK(ID IS NOT NULL)
,CONSTRAINT MA_PASSWORD_NN CHECK(PASSWORD IS NOT NULL)
);

--○ 교수등록 테이블 생성
CREATE TABLE TEACHER_REGISTER
(TEACHER_CODE    VARCHAR2(10)          --(교수코드)
,ID              VARCHAR2(20)          --(ID) 
,PASSWORD        VARCHAR2(30)          --(비밀번호)
,NAME            VARCHAR2(20)          --(교수명)
,SSN             VARCHAR2(13)          --(주민번호)
,REGISTER_DATE   DATE DEFAULT SYSDATE  --(가입일자)
,CONSTRAINT TC_CODE_PK PRIMARY KEY(TEACHER_CODE)
,CONSTRAINT TC_ID_NN CHECK(ID IS NOT NULL)
,CONSTRAINT TC_PASSWORD_NN CHECK(PASSWORD IS NOT NULL)
,CONSTRAINT TC_NAME_NN CHECK(NAME IS NOT NULL)
,CONSTRAINT TC_SSN_NN CHECK(SSN IS NOT NULL)
);










