SELECT USER
FROM DUAL;
--==>>TEAM4
--------------------------------------------------------------------------------
--○사용자테이블확인
SELECT TABLE_NAME
FROM USER_TABLES;
--==>>
/*
MANAGER_REGISTER
TEACHER_REGISTER
STUDENT_REGISTER
COURSE_OPEN
COURSE_REGISTER
STUDENT_DROP
DROP_REASON
CLASSROOM_REGISTER
COURSE
SUBJECT_OPEN
TEXTBOOK
SUBJECT
SCORE_INPUT
*/
--○ MANAGER_REGISTER 구조 및 제약조건 확인
DESC MANAGER_REGISTER;
--==>>
/*
이름            널?       유형           
------------- -------- ------------ 
MANAGER_CODE  NOT NULL VARCHAR2(10) 
PASSWORD               VARCHAR2(30) 
REGISTER_DATE          DATE
*/
SELECT *
FROM VIEW_CONSTCHECK
WHERE TABLE_NAME = 'MANAGER_REGISTER';
--==>>
/*
TEAM4	MA_PASSWORD_NN	MANAGER_REGISTER	C	PASSWORD	PASSWORD IS NOT NULL	
TEAM4	MA_CODE_PK	    MANAGER_REGISTER	P	MANAGER_CODE		
*/


--○TEACHER_REGISTER 구조확인
DESC TEACHER_REGISTER;
--==>>
/*
이름            널?       유형           
------------- -------- ------------ 
TEACHER_CODE  NOT NULL VARCHAR2(10) 
PASSWORD               VARCHAR2(30) 
NAME                   VARCHAR2(20) 
SSN                    VARCHAR2(13) 
REGISTER_DATE          DATE         
*/
SELECT *
FROM VIEW_CONSTCHECK
WHERE TABLE_NAME = 'TEACHER_REGISTER';
--==>>
/*
TEAM4	TC_PASSWORD_NN	TEACHER_REGISTER	C	PASSWORD	PASSWORD IS NOT NULL	
TEAM4	TC_NAME_NN	    TEACHER_REGISTER	C	NAME	NAME IS NOT NULL	
TEAM4	TC_SSN_NN	    TEACHER_REGISTER	C	SSN	SSN IS NOT NULL	
TEAM4	TC_CODE_PK	    TEACHER_REGISTER	P	TEACHER_CODE		
*/


--○STUDENT_REGISTER 구조확인
DESC STUDENT_REGISTER;
--==>>
/*
이름            널?       유형           
------------- -------- ------------ 
STUDENT_CODE  NOT NULL VARCHAR2(10) 
PASSWORD               VARCHAR2(30) 
NAME                   VARCHAR2(20) 
SSN                    VARCHAR2(13) 
REGISTER_DATE          DATE
*/
SELECT *
FROM VIEW_CONSTCHECK
WHERE TABLE_NAME = 'STUDENT_REGISTER';
--==>>
/*
TEAM4	STD_PASSWORD_NN	STUDENT_REGISTER	C	PASSWORD	    PASSWORD IS NOT NULL	
TEAM4	STD_NAME_NN	    STUDENT_REGISTER	C	NAME	        NAME IS NOT NULL	
TEAM4	STD_SSN_NN	    STUDENT_REGISTER	C	SSN	            SSN IS NOT NULL	
TEAM4	STD_REG_DATE_NN	STUDENT_REGISTER	C	REGISTER_DATE	REGISTER_DATE IS NOT NULL	
TEAM4	STD_STD_CODE_PK	STUDENT_REGISTER	P	STUDENT_CODE		
TEAM4	STD_SSN_UK	    STUDENT_REGISTER	U	SSN		
*/


--○COURSE_OPEN 구조확인
DESC COURSE_OPEN;
--==>>
/*
이름             널?       유형           
-------------- -------- ------------ 
OP_COURSE_CODE NOT NULL VARCHAR2(10) 
COURSE_CODE             NUMBER       
TEACHER_CODE            VARCHAR2(10) 
CLASSROOM_CODE          NUMBER       
START_DATE              DATE         
END_DATE                DATE         
OPEN_DATE               DATE
*/
SELECT *
FROM VIEW_CONSTCHECK
WHERE TABLE_NAME = 'COURSE_OPEN';
--==>>
/*
TEAM4	OP_COU_COU_CODE_NN	    COURSE_OPEN	C	COURSE_CODE	    COURSE_CODE IS NOT NULL	
TEAM4	OP_COU_CLA_CODE_NN	    COURSE_OPEN	C	CLASSROOM_CODE	CLASSROOM_CODE IS NOT NULL	
TEAM4	OP_COU_STA_DATE_NN	    COURSE_OPEN	C	START_DATE	    START_DATE IS NOT NULL	
TEAM4	OP_COU_END_DATE_NN	    COURSE_OPEN	C	END_DATE	    END_DATE IS NOT NULL	
TEAM4	OP_COU_OP_COU_CODE_PK	COURSE_OPEN	P	OP_COURSE_CODE		
TEAM4	OP_COU_COU_CODE_FK	    COURSE_OPEN	R	COURSE_CODE		                            NO ACTION
TEAM4	OP_COU_TEA_CODE_FK	    COURSE_OPEN	R	TEACHER_CODE		                        NO ACTION
TEAM4	OP_COU_CLA_CODE_FK	    COURSE_OPEN	R	CLASSROOM_CODE		                        NO ACTION
*/


--○COURSE_REGISTER 구조확인
DESC COURSE_REGISTER;
--==>>
/*
이름              널?       유형           
--------------- -------- ------------ 
REG_COURSE_CODE NOT NULL VARCHAR2(10) 
OP_COURSE_CODE  NOT NULL VARCHAR2(10) 
STUDENT_CODE    NOT NULL VARCHAR2(10) 
REG_COURSE_DATE          DATE 
*/
SELECT *
FROM VIEW_CONSTCHECK
WHERE TABLE_NAME = 'COURSE_REGISTER';
--==>>
/*
TEAM4	REG_COU_COU_CODE_NN	COURSE_REGISTER	C	OP_COURSE_CODE	"OP_COURSE_CODE" IS NOT NULL	
TEAM4	REG_COU_STD_CODE_NN	COURSE_REGISTER	C	STUDENT_CODE	"STUDENT_CODE" IS NOT NULL	
TEAM4	REG_COU_CODE_PK	COURSE_REGISTER	    P	REG_COURSE_CODE		
TEAM4	REG_COU_COU_CODE_FK	COURSE_REGISTER	R	OP_COURSE_CODE		                            NO ACTION
TEAM4	TEG_COU_STD_CODE_FK	COURSE_REGISTER	R	STUDENT_CODE		                            NO ACTION
*/


--○STUDENT_DROP 구조확인
DESC STUDENT_DROP;
--==>>
/*
이름              널?       유형           
--------------- -------- ------------ 
DROP_CODE       NOT NULL VARCHAR2(10) 
REG_COURSE_CODE NOT NULL VARCHAR2(10) 
DR_REASON_CODE           NUMBER       
DROP_DATE                DATE 
*/
SELECT *
FROM VIEW_CONSTCHECK
WHERE TABLE_NAME = 'STUDENT_DROP';
--==>>
/*
TEAM4	DR_STD_COU_CODE	STUDENT_DROP	    C	REG_COURSE_CODE	"REG_COURSE_CODE" IS NOT NULL	
TEAM4	DR_STD_CODE_PK	STUDENT_DROP	    P	DROP_CODE		
TEAM4	DR_STD_COU_CODE_FK	STUDENT_DROP	R	REG_COURSE_CODE		                            NO ACTION
TEAM4	DR_STD_RE_CODE_FK	STUDENT_DROP	R	DR_REASON_CODE		                            NO ACTION
*/


--○DROP_REASON 구조확인
DESC DROP_REASON;
--==>>
/*
이름             널?       유형           
-------------- -------- ------------ 
DR_REASON_CODE NOT NULL NUMBER       
DETAIL                  VARCHAR2(30) 
*/
SELECT *
FROM VIEW_CONSTCHECK
WHERE TABLE_NAME = 'DROP_REASON';
--==>>
/*
TEAM4	DR_RE_DET_NN	DROP_REASON	C	DETAIL	        DETAIL IS NOT NULL	
TEAM4	DR_RE_CODE_PK	DROP_REASON	P	DR_REASON_CODE		
*/


--○CLASSROOM_REGISTER 구조확인
DESC CLASSROOM_REGISTER;
--==>>
/*
이름                 널?       유형           
------------------ -------- ------------ 
CLASSROOM_CODE     NOT NULL NUMBER       
CLASSROOM_NAME              VARCHAR2(20) 
CLASSROOM_CAPACITY          NUMBER 
*/
SELECT *
FROM VIEW_CONSTCHECK
WHERE TABLE_NAME = 'CLASSROOM_REGISTER';
--==>>
/*
TEAM4	REG_CLASS_NAME_NN	CLASSROOM_REGISTER	C	CLASSROOM_NAME	CLASSROOM_NAME IS NOT NULL	
TEAM4	REG_CLASS_CAPA_NN	CLASSROOM_REGISTER	C	CLASSROOM_CAPACITY	CLASSROOM_CAPACITY IS NOT NULL	
TEAM4	REG_CLASS_CODE_PK	CLASSROOM_REGISTER	P	CLASSROOM_CODE		
*/


--○COURSE 구조확인
DESC COURSE;
--==>>
/*
이름          널?       유형           
----------- -------- ------------ 
COURSE_CODE NOT NULL NUMBER       
COURSE_NAME          VARCHAR2(20) 
*/
SELECT *
FROM VIEW_CONSTCHECK
WHERE TABLE_NAME = 'COURSE';
--==>>
/*
TEAM4	COU_NAME_NN	COURSE	C	COURSE_NAME	COURSE_NAME IS NOT NULL	
TEAM4	COU_CODE_PK	COURSE	P	COURSE_CODE		
*/


--○SUBJECT_OPEN 구조확인
DESC SUBJECT_OPEN;
--==>>
/*
이름               널?       유형           
---------------- -------- ------------ 
OP_SUBJECT_CODE  NOT NULL VARCHAR2(10) 
SUBJECT_CODE              NUMBER       
TEXTBOOK_CODE             NUMBER       
OP_COURSE_CODE            VARCHAR2(10) 
START_DATE                DATE         
END_DATE                  DATE         
ATTENDANCE_RATE           NUMBER       
WRITING_RATE              NUMBER       
PERFORMANCE_RATE          NUMBER       
OPEN_DATE                 DATE
*/
SELECT *
FROM VIEW_CONSTCHECK
WHERE TABLE_NAME = 'SUBJECT_OPEN';
--==>>
/*
TEAM4	OP_SUB_SUB_CODE_NN	    SUBJECT_OPEN	C	SUBJECT_CODE	SUBJECT_CODE IS NOT NULL	
TEAM4	OP_SUB_OP_COU_CODE_NN	SUBJECT_OPEN	C	OP_COURSE_CODE	OP_COURSE_CODE IS NOT NULL	
TEAM4	OP_SUB_STR_DATE_NN	    SUBJECT_OPEN	C	START_DATE	START_DATE IS NOT NULL	
TEAM4	OP_SUB_END_DATE_NN	    SUBJECT_OPEN	C	END_DATE	END_DATE IS NOT NULL	
TEAM4	OP_SUB_CODE_PK	        SUBJECT_OPEN	P	OP_SUBJECT_CODE		
TEAM4	OP_SUB_SUB_CODE_FK	    SUBJECT_OPEN	R	SUBJECT_CODE		NO ACTION
TEAM4	OP_SUB_TXT_CODE_FK	    SUBJECT_OPEN	R	TEXTBOOK_CODE		NO ACTION
TEAM4	OP_SUB_OP_COU_CODE_FK	SUBJECT_OPEN	R	OP_COURSE_CODE		NO ACTION
*/


--○TEXTBOOK구조확인
DESC TEXTBOOK;
--==>>
/*
이름            널?       유형           
------------- -------- ------------ 
TEXTBOOK_CODE NOT NULL NUMBER       
TEXTBOOK_NAME          VARCHAR2(20) 
PUBLISHER              VARCHAR2(30) 
*/
SELECT *
FROM VIEW_CONSTCHECK
WHERE TABLE_NAME = 'TEXTBOOK';
--==>>
/*
TEAM4	TXT_CODE_PK	TEXTBOOK	P	TEXTBOOK_CODE		
TEAM4	TXT_NAME_NN	TEXTBOOK	C	TEXTBOOK_NAME	"TEXTBOOK_NAME" IS NOT NULL	
*/


--○SUBJECT 구조확인
DESC SUBJECT;
--==>>
/*
이름           널?       유형           
------------ -------- ------------ 
SUBJECT_CODE NOT NULL NUMBER       
SUBJECT_NAME          VARCHAR2(20) 
*/
SELECT *
FROM VIEW_CONSTCHECK
WHERE TABLE_NAME = 'SUBJECT';
--==>>
/*
TEAM4	SUB_CODE_PK	SUBJECT	P	SUBJECT_CODE		
TEAM4	SUB_NAME_NN	SUBJECT	C	SUBJECT_NAME	"SUBJECT_NAME" IS NOT NULL	
*/


--○SCORE_INPUT 구조확인
DESC SCORE_INPUT;
--==>>
/*
이름                널?       유형           
----------------- -------- ------------ 
SCORE_CODE        NOT NULL VARCHAR2(10) 
OP_SUBJECT_CODE            VARCHAR2(10) 
REG_COURSE_CODE            VARCHAR2(10) 
ATTENDANCE_SCORE           NUMBER       
WRITING_SCORE              NUMBER       
PERFORMANCE_SCORE          NUMBER       
SCORE_DATE                 DATE    
*/
SELECT *
FROM VIEW_CONSTCHECK
WHERE TABLE_NAME = 'SCORE_INPUT';
--==>>
/*
TEAM4	IN_SCR_CODE_PK	SCORE_INPUT	P	SCORE_CODE		
TEAM4	IN_SCR_OP_SUB_CODE_NN	        SCORE_INPUT	C	OP_SUBJECT_CODE	"OP_SUBJECT_CODE" IS NOT NULL	
TEAM4	IN_SCR_REG_COU_CODE_NN	        SCORE_INPUT	C	REG_COURSE_CODE	"REG_COURSE_CODE" IS NOT NULL	
TEAM4	IN_SCR_OP_SUB_CODE_FK	        SCORE_INPUT	R	OP_SUBJECT_CODE		NO ACTION
TEAM4	IN_SCR_REG_COU_CODE_FK	        SCORE_INPUT	R	REG_COURSE_CODE		NO ACTION
*/
--------------------------------------------------------------------------------
SELECT *
FROM USER_PROCEDURES;

--프로시저 삭제
SELECT 'DROP PROCEDURE ' || OBJECT_NAME || ';'
FROM USER_PROCEDURES
WHERE OBJECT_NAME LIKE 'PRC%';

DROP PROCEDURE PRC_LOGIN;
DROP PROCEDURE PRC_OP_COU_INSERT;
DROP PROCEDURE PRC_OP_SUB_INSERT;
DROP PROCEDURE PRC_SUB_OP_SELECT;
DROP PROCEDURE PRC_TC_INSERT;
DROP PROCEDURE PRC_TC_SELECT;

--함수 삭제
SELECT 'DROP FUNCTION ' || OBJECT_NAME || ';'
FROM USER_PROCEDURES
WHERE OBJECT_NAME LIKE 'FN%';

DROP FUNCTION FN_ID_CHECK;
DROP FUNCTION FN_PW_CHECK;

--트리거 삭제
SELECT 'DROP TRIGGER ' || OBJECT_NAME || ';'
FROM USER_PROCEDURES
WHERE OBJECT_NAME LIKE 'TRG%';

DROP TRIGGER TRG_TC_DELETE;

--테스트 데이터 삭제 - 완료
SELECT TABLE_NAME
FROM USER_TABLES;
--------------------------------------------------------------------------------
--★함수생성★--

--------------------------------------------------------------------------------
-- *2
--○ 아이디 조회 함수 FN_ID_CHECK(ID)
CREATE OR REPLACE FUNCTION FN_ID_CHECK
(ID MANAGER_REGISTER.MANAGER_CODE%TYPE)
RETURN NUMBER 
IS
    V_M NUMBER;
    V_T NUMBER;
    V_S NUMBER;
    V_RESULT NUMBER;
BEGIN
    SELECT COUNT(*) INTO V_T
    FROM TEACHER_REGISTER
    WHERE TEACHER_CODE = ID;
    
    SELECT COUNT(*) INTO V_M
    FROM MANAGER_REGISTER
    WHERE MANAGER_CODE = ID;
    
    SELECT COUNT(*) INTO V_S
    FROM STUDENT_REGISTER
    WHERE STUDENT_CODE = ID;
    
    IF (SUBSTR(ID,1,1) = 'M')
        THEN V_RESULT := V_M;
    ELSIF (SUBSTR(ID,1,1) = 'T')
        THEN V_RESULT := V_T;
    ELSIF (SUBSTR(ID,1,1) = 'S')
        THEN V_RESULT := V_S;
    ELSE
        V_RESULT := 0;
    END IF;
 
    RETURN V_RESULT;    -- 반환 : 일치하는 ID가 있으면 1, 없으면 0
END;
--==>>Function FN_ID_CHECK이(가) 컴파일되었습니다.
--------------------------------------------------------------------------------
-- *3
--○ 비밀번호 조회 함수 FN_PW_CHECK(ID,PW)
CREATE OR REPLACE FUNCTION FN_PW_CHECK
( CODE MANAGER_REGISTER.MANAGER_CODE%TYPE
, PW MANAGER_REGISTER.PASSWORD%TYPE)
RETURN NUMBER 
IS
    V_M NUMBER;
    V_T NUMBER;
    V_S NUMBER;
    V_RESULT    NUMBER;
BEGIN
    SELECT COUNT(*) INTO V_M
    FROM MANAGER_REGISTER
    WHERE PASSWORD = PW
      AND MANAGER_CODE = CODE;

    SELECT COUNT(*) INTO V_T
    FROM TEACHER_REGISTER
    WHERE PASSWORD = PW
      AND TEACHER_CODE = CODE;
    
    SELECT COUNT(*) INTO V_S
    FROM STUDENT_REGISTER
    WHERE PASSWORD = PW
      AND STUDENT_CODE = CODE;
    
    IF (V_M = 1 AND V_T = 0 AND V_S = 0)
    THEN V_RESULT := V_M;
    ELSIF (V_T = 1 AND V_M = 0 AND V_S = 0)
    THEN V_RESULT := V_T;
    ELSIF (V_S = 1 AND V_M = 0 AND V_T = 0)
    THEN V_RESULT := V_S;
    ELSE
        V_RESULT := 0;
    END IF;
 
    RETURN V_RESULT;    -- 반환 : 일치하는 PW가 있으면 1, 없으면 0
END;

--------------------------------------------------------------------------------

-- *12
--○ 과정명 반환 함수 FN_COURSE(과정코드)
CREATE OR REPLACE FUNCTION FN_COURSE(V_COU_COD NUMBER)
RETURN VARCHAR2
IS
    V_COU_NAME   COURSE.COURSE_NAME%TYPE;
BEGIN
    SELECT COURSE_NAME INTO V_COU_NAME
      FROM COURSE
     WHERE COURSE_CODE = V_COU_COD;
     
     RETURN V_COU_NAME;
END;
--==>>Function FN_COURSE이(가) 컴파일되었습니다.

--------------------------------------------------------------------------------
-- *13
--○ 교수명 반환 함수 FN_TEACHER_REGISTER(교수ID)
CREATE OR REPLACE FUNCTION FN_TEACHER_REGISTER(V_TC_COD VARCHAR2)
RETURN  VARCHAR2
IS
    V_NAME  TEACHER_REGISTER.NAME%TYPE;
BEGIN
    SELECT NAME INTO V_NAME
      FROM TEACHER_REGISTER
     WHERE TEACHER_CODE = V_TC_COD;
    
    RETURN V_NAME;
END;
--==>>Function FN_TEACHER_REGISTER이(가) 컴파일되었습니다.
--------------------------------------------------------------------------------

-- *14
--○ 강의실명 반환 함수 FN_CLASSROOM_REGISTER(강의실코드) 
CREATE OR REPLACE FUNCTION FN_CLASSROOM_REGISTER(V_CLAS_COD NUMBER)
RETURN  VARCHAR2
IS
    V_CLAS_NAME    CLASSROOM_REGISTER.CLASSROOM_NAME%TYPE;
BEGIN
    SELECT CLASSROOM_NAME INTO V_CLAS_NAME
      FROM CLASSROOM_REGISTER
     WHERE CLASSROOM_CODE = V_CLAS_COD;
    
    RETURN V_CLAS_NAME;
END;
--==>>Function FN_CLASSROOM_REGISTER이(가) 컴파일되었습니다.
--------------------------------------------------------------------------------

-- *15
--○ 교재명 반환 함수 FN_TEXTBOOK(교재코드)
CREATE OR REPLACE FUNCTION FN_TEXTBOOK(V_TXT_COD  NUMBER)
RETURN  VARCHAR2
IS
    V_TXT_NAME     TEXTBOOK.TEXTBOOK_NAME%TYPE;
BEGIN
    SELECT TEXTBOOK_NAME INTO V_TXT_NAME
      FROM TEXTBOOK
     WHERE TEXTBOOK_CODE = V_TXT_COD;
     
     RETURN V_TXT_NAME;
END;
--==>>Function FN_TEXTBOOK이(가) 컴파일되었습니다.
--------------------------------------------------------------------------------
-- *16
--○ 과목명 반환 함수 FN_SUBJECT(과목코드)
CREATE OR REPLACE FUNCTION FN_SUBJECT(V_SUB_COD NUMBER)
RETURN  VARCHAR2
IS
    V_SUB_NAME  SUBJECT.SUBJECT_NAME%TYPE;
BEGIN
    SELECT SUBJECT_NAME INTO V_SUB_NAME
      FROM SUBJECT
     WHERE SUBJECT_CODE = V_SUB_COD;
     
     RETURN V_SUB_NAME;
END;
--==>>Function FN_SUBJECT이(가) 컴파일되었습니다.
--------------------------------------------------------------------------------
--★프로시저 생성★--
--------------------------------------------------------------------------------
-- *1
-- [공통]
--○ 로그인 프로시저 PRC_LOGIN(ID,PW)
CREATE OR REPLACE PROCEDURE PRC_LOGIN
( V_CODE  IN MANAGER_REGISTER.MANAGER_CODE%TYPE --관리자PK, 학생PK, 교수PK 모두 VARCHAR2(10)
, V_PW    IN MANAGER_REGISTER.PASSWORD%TYPE     --관리자PW, 학생PW, 교수PW 모두 VARCHAR2(30)
)
IS
    V_CHECKID NUMBER;   --일치1, 불일치0
    V_CHECKPW NUMBER;   --일치1, 불일치0
    
    USER_DEFINE_ERROR1 EXCEPTION;           -- ID 없음 에러
    USER_DEFINE_ERROR2 EXCEPTION;           -- 불일치 에러
BEGIN
    V_CHECKID := FN_ID_CHECK(V_CODE);
    V_CHECKPW := FN_PW_CHECK(V_CODE, V_PW);
   
    -- 로그인 IF문
    IF (V_CHECKID = 1 AND V_CHECKPW = 1)
        THEN DBMS_OUTPUT.PUT_LINE('로그인 성공~!!!');
    ELSIF (V_CHECKID = 0)
        THEN RAISE USER_DEFINE_ERROR1;
    ELSE
        RAISE USER_DEFINE_ERROR2;
    END IF;
    
    -- 로그인 실패 예외 처리
    EXCEPTION
       WHEN USER_DEFINE_ERROR1
            THEN RAISE_APPLICATION_ERROR(-20100, '해당 아이디가 존재하지 않습니다.');
                ROLLBACK;
       WHEN USER_DEFINE_ERROR2
            THEN RAISE_APPLICATION_ERROR(-20103, '아이디, 비밀번호가 일치하지 않습니다.');
                ROLLBACK;
       WHEN OTHERS
            THEN ROLLBACK;

    -- 커밋
    COMMIT;
END;
--==>>Procedure PRC_LOGIN이(가) 컴파일되었습니다.
--------------------------------------------------------------------------------

-- *4
-- [관리자]
--○ 관리자계정 PW변경 프로시저 PRC_MA_PW_CHANGE(ID,PW,NEWPW)
CREATE OR REPLACE PROCEDURE PRC_MA_PW_CHANGE
( V_CODE  IN MANAGER_REGISTER.MANAGER_CODE%TYPE
, V_PW    IN MANAGER_REGISTER.PASSWORD%TYPE
, V_NEWPW IN MANAGER_REGISTER.PASSWORD%TYPE)
IS
    V_PW2 MANAGER_REGISTER.PASSWORD%TYPE;
    
    USER_DEFINE_ERROR EXCEPTION;
BEGIN
    
    SELECT PASSWORD INTO V_PW2
    FROM MANAGER_REGISTER
    WHERE MANAGER_CODE = V_CODE;
    
    IF (V_PW = V_PW2)
        THEN UPDATE MANAGER_REGISTER
             SET PASSWORD = V_NEWPW
             WHERE MANAGER_CODE = V_CODE;
    ELSE
        RAISE USER_DEFINE_ERROR;
    END IF;
    
    -- 커밋
    COMMIT;
    
    EXCEPTION
       WHEN USER_DEFINE_ERROR
            THEN RAISE_APPLICATION_ERROR(-20103, '아이디, 비밀번호가 일치하지 않습니다.');
            ROLLBACK;
END;
--==>>Procedure PRC_MA_PW_CHANGE이(가) 컴파일되었습니다.
-- *10
--○ 관리자의 교수자 정보 변경 프로시저 TEACHER_REGISTER_UPDATE(ID,PW,이름,주민번호,수정일자)
CREATE OR REPLACE PROCEDURE TEACHER_REGISTER_UPDATE
( V_TC_COD        IN TEACHER_REGISTER.TEACHER_CODE%TYPE
, V_PW            IN TEACHER_REGISTER.PASSWORD%TYPE
, V_NAME          IN TEACHER_REGISTER.NAME%TYPE
, V_SSN           IN TEACHER_REGISTER.SSN%TYPE
, V_REG_DATE      IN TEACHER_REGISTER.REGISTER_DATE%TYPE
)
IS
    TEMP_TC_COD     NUMBER;
    
    TC_COD_ERROR    EXCEPTION;
BEGIN
    SELECT COUNT(*) INTO TEMP_TC_COD
      FROM TEACHER_REGISTER
     WHERE TEACHER_CODE = V_TC_COD;
    
    IF(TEMP_TC_COD = 0)
        THEN RAISE TC_COD_ERROR;
    END IF;
    
    UPDATE TEACHER_REGISTER
       SET PASSWORD = V_PW, NAME = V_NAME, SSN = V_SSN
         , REGISTER_DATE = V_REG_DATE
     WHERE TEACHER_CODE = V_TC_COD;

    EXCEPTION
        WHEN TC_COD_ERROR
            THEN RAISE_APPLICATION_ERROR(-20202, '유효한 교수가 아닙니다.');
END;
--==>>Procedure TEACHER_REGISTER_UPDATE이(가) 컴파일되었습니다.
-- *27
--○ 학생 등록 삭제 PRC_STD_DELETE(학생ID)
CREATE OR REPLACE PROCEDURE PRC_STD_DELETE
(V_STD_COD IN STUDENT_REGISTER.STUDENT_CODE%TYPE)
IS
    TEMP_STD_COD   NUMBER; 
    TEMP_STD_FK    NUMBER;
    STD_COD_ERROR   EXCEPTION; 
    STD_DEL_ERROR   EXCEPTION; 
BEGIN
    SELECT COUNT(*) INTO TEMP_STD_COD
    FROM STUDENT_REGISTER
    WHERE STUDENT_CODE = V_STD_COD;    
     
    SELECT COUNT(*) INTO TEMP_STD_FK
    FROM COURSE_REGISTER
    WHERE STUDENT_CODE = V_STD_COD;        

    IF ( TEMP_STD_COD  = 0)   
        THEN RAISE STD_COD_ERROR;
    ELSIF (TEMP_STD_FK <> 0  )
        THEN RAISE STD_DEL_ERROR;
    END IF; 
    
    DELETE 
    FROM STUDENT_REGISTER
    WHERE STUDENT_CODE = V_STD_COD;
    
    EXCEPTION       
        WHEN STD_COD_ERROR
            THEN RAISE_APPLICATION_ERROR(-20505, '학생이 존재하지 않습니다.');
            ROLLBACK;           
        WHEN STD_DEL_ERROR
            THEN RAISE_APPLICATION_ERROR(-20206, '해당 학생이 참조되고 있으므로 삭제가 불가능합니다.');
            ROLLBACK;        
        WHEN OTHERS
            THEN ROLLBACK;
     COMMIT;
END;
--==>>Procedure PRC_STD_DELETE이(가) 컴파일되었습니다.
-- *18
--○ 과정개설 정보 변경 프로시저 
--   PRC_OP_COU_UPDATE(과정개설코드,과정코드,교수ID,강의실코드,시작일자,종료일자,개설일자)
CREATE OR REPLACE PROCEDURE PRC_OP_COU_UPDATE
( V_OPC_COD         IN COURSE_OPEN.OP_COURSE_CODE%TYPE
, V_COU_COD         IN COURSE_OPEN.COURSE_CODE%TYPE
, V_TC_COD          IN COURSE_OPEN.TEACHER_CODE%TYPE
, V_CLAS_COD        IN COURSE_OPEN.CLASSROOM_CODE%TYPE
, V_SDATE           IN COURSE_OPEN.START_DATE%TYPE
, V_EDATE           IN COURSE_OPEN.END_DATE%TYPE
, V_OPDATE          IN COURSE_OPEN.OPEN_DATE%TYPE 
)
IS
    TEMP_OPC_COD    NUMBER;
    TEMP_COU_COD    NUMBER;
    TEMP_TC_COD     NUMBER;
    TEMP_CLAS_COD   NUMBER;
    
    OPC_COD_ERROR   EXCEPTION;  -- 과정코드가 존재하지 않을 경우
    COU_COD_ERROR   EXCEPTION;  -- 과목코드가 존재하지 않을 경우
    TC_COD_ERROR    EXCEPTION;  -- 교수코드가 존재하지 않을 경우
    CLAS_COD_ERROR  EXCEPTION;  -- 강의실코드가 존재하지 않을 경우
    DATE_ERROR1     EXCEPTION;  -- 날짜가 적합하지 않은 경우 발생하는 에러
BEGIN
    -- 과정코드 존재 확인
    SELECT COUNT(*) INTO TEMP_OPC_COD
      FROM COURSE_OPEN
     WHERE OP_COURSE_CODE = V_OPC_COD;
     
    IF (TEMP_OPC_COD = 0)
        THEN RAISE OPC_COD_ERROR;
    END IF;
    
    -- 과목코드 존재확인
    SELECT COUNT(*) INTO TEMP_COU_COD
      FROM COURSE
     WHERE COURSE_CODE = V_COU_COD;
    
    IF(TEMP_COU_COD = 0)
        THEN RAISE COU_COD_ERROR;
    END IF;
    
    -- 교수코드 확인
    SELECT COUNT(*) INTO TEMP_TC_COD
      FROM TEACHER_REGISTER
     WHERE TEACHER_CODE = V_TC_COD;
    
    IF(TEMP_TC_COD = 0)
        THEN RAISE TC_COD_ERROR;
    END IF;
    
    -- 강의실 코드 확인
    SELECT COUNT(*) INTO TEMP_CLAS_COD
      FROM CLASSROOM_REGISTER
     WHERE CLASSROOM_CODE = V_CLAS_COD;
    
    IF(TEMP_CLAS_COD = 0)
        THEN RAISE CLAS_COD_ERROR;
    END IF;
    
    -- 날짜 확인
    IF((V_SDATE > V_EDATE) OR (V_OPDATE > V_EDATE))
        THEN RAISE DATE_ERROR1;
    END IF;

    UPDATE COURSE_OPEN
       SET COURSE_CODE = V_COU_COD, TEACHER_CODE = V_TC_COD
         , CLASSROOM_CODE = V_CLAS_COD
         , START_DATE = V_SDATE, END_DATE = V_EDATE
         , OPEN_DATE = V_OPDATE
     WHERE OP_COURSE_CODE = V_OPC_COD;
     
    COMMIT;
    
    EXCEPTION
        WHEN OPC_COD_ERROR
            THEN RAISE_APPLICATION_ERROR(-20201, '유효한 과정이 아닙니다.');
            ROLLBACK;
        WHEN COU_COD_ERROR
            THEN RAISE_APPLICATION_ERROR(-20300, '유효한 과목이 아닙니다.');
        WHEN TC_COD_ERROR
            THEN RAISE_APPLICATION_ERROR(-20202, '유효한 교수가 아닙니다.');
        WHEN CLAS_COD_ERROR
            THEN RAISE_APPLICATION_ERROR(-20203, '유효한 강의실이 아닙니다.');
        WHEN DATE_ERROR1
            THEN RAISE_APPLICATION_ERROR(-20204, '날짜를 확인하세요.');
        WHEN OTHERS
            THEN ROLLBACK;
END;
--==>>Procedure PRC_OP_COU_UPDATE이(가) 컴파일되었습니다.
-- *28
--○ 과정개설 삭제 프로시저 PRC_OP_COU_DELETE(과정개설코드)
CREATE OR REPLACE PROCEDURE PRC_OP_COU_DELETE
(V_OP_COU_COD  IN COURSE_OPEN.OP_COURSE_CODE%TYPE)
IS
    TEMP_OP_COU_COD   NUMBER; 
    TEMP_OP_COU_FK    NUMBER;
    OP_COU_COD_ERROR   EXCEPTION; 
    OP_COU_DEL_ERROR   EXCEPTION; 
BEGIN
    SELECT COUNT(*) INTO TEMP_OP_COU_COD
    FROM COURSE_OPEN
     WHERE OP_COURSE_CODE = V_OP_COU_COD;    
     
    SELECT COUNT(*) INTO TEMP_OP_COU_FK
    FROM COURSE_REGISTER
     WHERE OP_COURSE_CODE = V_OP_COU_COD;        

    IF (TEMP_OP_COU_COD  = 0)   
        THEN RAISE OP_COU_COD_ERROR;
    ELSIF (TEMP_OP_COU_FK <> 0  )
        THEN RAISE OP_COU_DEL_ERROR;
    END IF; 

    DELETE
    FROM COURSE_OPEN
    WHERE OP_COURSE_CODE = V_OP_COU_COD;
    
     EXCEPTION       
        WHEN OP_COU_COD_ERROR
            THEN RAISE_APPLICATION_ERROR(-20201, '유효한 과정이 아닙니다.');
            ROLLBACK;           
        WHEN OP_COU_DEL_ERROR
            THEN RAISE_APPLICATION_ERROR(-20206, '해당 과정은 참조되고 있으므로 삭제가 불가능합니다.');
            ROLLBACK;        
        WHEN OTHERS
            THEN ROLLBACK;
     COMMIT;
END;
--==>>Procedure PRC_OP_COU_DELETE이(가) 컴파일되었습니다.
-- *29
--○ 과목개설 삭제 프로시저 PRC_OP_SUB_DELETE(과목개설코드)
CREATE OR REPLACE PROCEDURE PRC_OP_SUB_DELETE
(V_OP_SUB_COD  IN SUBJECT_OPEN.OP_SUBJECT_CODE%TYPE)
IS
    TEMP_OP_SUB_COD   NUMBER; 
    TEMP_OP_SUB_FK    NUMBER;
    OP_SUB_COD_ERROR   EXCEPTION; 
    OP_SUB_DEL_ERROR   EXCEPTION; 
BEGIN
    SELECT COUNT(*) INTO TEMP_OP_SUB_COD 
    FROM SUBJECT_OPEN
     WHERE OP_SUBJECT_CODE = V_OP_SUB_COD;    
     
    SELECT COUNT(*) INTO TEMP_OP_SUB_FK 
    FROM SCORE_INPUT
     WHERE OP_SUBJECT_CODE = V_OP_SUB_COD;       

    
    IF (TEMP_OP_SUB_COD  = 0)   
        THEN RAISE OP_SUB_COD_ERROR;
    ELSIF (TEMP_OP_SUB_FK  <> 0  )
        THEN RAISE OP_SUB_DEL_ERROR;
    END IF; 

    DELETE
    FROM SUBJECT_OPEN
    WHERE OP_SUBJECT_CODE = V_OP_SUB_COD;
    
     EXCEPTION       
        WHEN OP_SUB_COD_ERROR
            THEN RAISE_APPLICATION_ERROR(-20300, '유효한 과목이 아닙니다.');
            ROLLBACK;           
        WHEN OP_SUB_DEL_ERROR
            THEN RAISE_APPLICATION_ERROR(-20308, '해당 과목은 참조되고 있으므로 삭제가 불가능합니다.');
            ROLLBACK;        
        WHEN OTHERS
            THEN ROLLBACK;
     COMMIT;
END;
--==>>Procedure PRC_OP_SUB_DELETE이(가) 컴파일되었습니다.
-- *19
--○ 과정 변경 프로시저 PRC_COURSE_UPDATE(과정코드,과정명)
CREATE OR REPLACE PROCEDURE PRC_COURSE_UPDATE
( V_COU_COD     IN COURSE.COURSE_CODE%TYPE
, V_COU_NAME    IN COURSE.COURSE_NAME%TYPE
)
IS
    TEMP_COU_COD    NUMBER;
    
    COU_COD_ERROR   EXCEPTION;
BEGIN
    SELECT COUNT(*) INTO TEMP_COU_COD
      FROM COURSE
     WHERE COURSE_CODE = V_COU_COD;
     
    IF (TEMP_COU_COD = 0)
        THEN RAISE COU_COD_ERROR;
    END IF;

    UPDATE COURSE
       SET COURSE_NAME = V_COU_NAME
     WHERE COURSE_CODE = V_COU_COD;
     
    EXCEPTION
        WHEN COU_COD_ERROR
            THEN RAISE_APPLICATION_ERROR(-20201, '유효한 과정이 아닙니다.');
                ROLLBACK;
        WHEN OTHERS
            THEN ROLLBACK;
    COMMIT;
END;
--==>>Procedure PRC_COURSE_UPDATE이(가) 컴파일되었습니다.
-- *24
--○ 과정 삭제 프로시저 PRC_COURSE_DELETE(과정코드)
CREATE OR REPLACE PROCEDURE PRC_COURSE_DELETE
(V_COU_COD  IN COURSE.COURSE_CODE%TYPE)
IS
    TEMP_COU_COD    NUMBER;
    TEMP_COU_FK    NUMBER;
    COU_COD_ERROR   EXCEPTION; 
    COU_DEL_ERROR   EXCEPTION; 
BEGIN
    SELECT COUNT(*) INTO TEMP_COU_COD
      FROM COURSE
     WHERE COURSE_CODE = V_COU_COD;      
     
    SELECT COUNT(*) INTO TEMP_COU_FK
      FROM COURSE_OPEN
     WHERE COURSE_CODE = V_COU_COD;   
                                      
    IF(TEMP_COU_COD = 0)   
        THEN RAISE COU_COD_ERROR;
    ELSIF (TEMP_COU_FK <> 0)
        THEN RAISE COU_DEL_ERROR;
    END IF;
    
    -- DELETE
    DELETE
      FROM COURSE
     WHERE COURSE_CODE = V_COU_COD;
     
    EXCEPTION       
        WHEN COU_COD_ERROR
            THEN RAISE_APPLICATION_ERROR(-20201, '유효한 과정이 아닙니다.');
            ROLLBACK;         
        WHEN COU_DEL_ERROR 
            THEN RAISE_APPLICATION_ERROR(-20206, '해당 과정은 참조되고 있으므로 삭제가 불가능합니다.');
            ROLLBACK; 
        WHEN OTHERS
            THEN ROLLBACK;
    COMMIT;
END;
--==>>Procedure PRC_COURSE_DELETE이(가) 컴파일되었습니다.
-- *22
--○ 과목 변경 프로시저 PRC_SUB_MANEDIT(과목코드,과목명)
CREATE OR REPLACE PROCEDURE PRC_SUB_MANEDIT
( V_SUB_COD    IN SUBJECT.SUBJECT_CODE%TYPE
, V_SUB_NAME   IN SUBJECT.SUBJECT_NAME%TYPE
)
IS
    TEMP_SUB_COD    NUMBER;
    
    SUB_COD_ERROR   EXCEPTION;
BEGIN
    SELECT COUNT(*) INTO TEMP_SUB_COD
      FROM SUBJECT
     WHERE SUBJECT_CODE = V_SUB_COD;
     
    IF(TEMP_SUB_COD = 0)
        THEN RAISE SUB_COD_ERROR;
    END IF;

    --UPDATE
    UPDATE SUBJECT
    SET SUBJECT_NAME = V_SUB_NAME
    WHERE SUBJECT_CODE = V_SUB_COD;  

    EXCEPTION
        WHEN SUB_COD_ERROR
            THEN RAISE_APPLICATION_ERROR(-20300, '유효한 과목이 아닙니다.');
                ROLLBACK;
        WHEN OTHERS
            THEN ROLLBACK;
    COMMIT;   
END;
--==>>Procedure PRC_SUB_MANEDIT이(가) 컴파일되었습니다.
-- *25
--○ 과목 삭제 프로시저 PRC_SUBJECT_DELETE(과목코드)
CREATE OR REPLACE PROCEDURE PRC_SUBJECT_DELETE
(V_SUB_COD IN SUBJECT.SUBJECT_CODE%TYPE
)
IS
    TEMP_SUB_COD    NUMBER;
    TEMP_SUB_FK     NUMBER;
    SUB_COD_ERROR   EXCEPTION;
    SUB_DEL_ERROR   EXCEPTION;
BEGIN
    SELECT COUNT(*) INTO TEMP_SUB_COD
      FROM SUBJECT
     WHERE SUBJECT_CODE = V_SUB_COD; 
     
     SELECT COUNT(*) INTO TEMP_SUB_FK
     FROM SUBJECT_OPEN
     WHERE SUBJECT_CODE = V_SUB_COD;
                                      
    IF(TEMP_SUB_COD = 0)   
        THEN RAISE SUB_COD_ERROR;
    ELSIF (TEMP_SUB_FK <> 0)
        THEN RAISE SUB_DEL_ERROR;
    END IF;
    -- DELETE
    DELETE
      FROM SUBJECT
     WHERE SUBJECT_CODE = V_SUB_COD; 
     
    EXCEPTION       
        WHEN SUB_COD_ERROR
            THEN RAISE_APPLICATION_ERROR(-20300, '유효한 과목이 아닙니다.');
        WHEN SUB_DEL_ERROR
            THEN RAISE_APPLICATION_ERROR(-20308, '해당 과목은 참조되고 있으므로 삭제가 불가능합니다.');
            ROLLBACK;           
        WHEN OTHERS
            THEN ROLLBACK;
     COMMIT;
END;
--==>>Procedure PRC_SUBJECT_DELETE이(가) 컴파일되었습니다.
-- *21
--○ 교재 변경 프로시저 PRC_TEXTBOOK_UPDATE(교재코드,교재명,출판사)
CREATE OR REPLACE PROCEDURE PRC_TEXTBOOK_UPDATE
( V_TXT_COD     IN TEXTBOOK.TEXTBOOK_CODE%TYPE
, V_TXT_NAME    IN TEXTBOOK.TEXTBOOK_NAME%TYPE
, V_PUBLISH     IN TEXTBOOK.PUBLISHER%TYPE
)
IS
    TEMP_TXT_COD    NUMBER;
    
    TXT_COD_ERROR   EXCEPTION;
BEGIN
    SELECT COUNT(*) INTO TEMP_TXT_COD
      FROM TEXTBOOK
     WHERE TEXTBOOK_CODE = V_TXT_COD;
     
    IF (TEMP_TXT_COD = 0)
        THEN RAISE TXT_COD_ERROR;
    END IF;
    
    UPDATE TEXTBOOK
       SET TEXTBOOK_NAME = V_TXT_NAME
         , PUBLISHER = V_PUBLISH
     WHERE TEXTBOOK_CODE = V_TXT_COD;
     
     EXCEPTION
        WHEN TXT_COD_ERROR
            THEN RAISE_APPLICATION_ERROR(-20307, '유효한 교재가 아닙니다.');
                ROLLBACK;
        WHEN OTHERS
            THEN ROLLBACK;    
    COMMIT;
END;

-- *23
--○ 강의실 삭제 프로시저 PRC_CLASSROOM_DLETE(강의실코드)
CREATE OR REPLACE PROCEDURE PRC_CLASSROOM_DLETE
(V_CLAS_COD   IN CLASSROOM_REGISTER.CLASSROOM_CODE%TYPE)
IS
    TEMP_CLAS_COD   NUMBER; 
    TEMP_CLAS_FK    NUMBER;
    CLAS_COD_ERROR   EXCEPTION; 
    CLAS_DEL_ERROR   EXCEPTION; 
BEGIN
    SELECT COUNT(*) INTO TEMP_CLAS_COD
      FROM CLASSROOM_REGISTER
     WHERE CLASSROOM_CODE = V_CLAS_COD;    
     
    SELECT COUNT(*) INTO TEMP_CLAS_FK
      FROM COURSE_OPEN
     WHERE CLASSROOM_CODE = V_CLAS_COD;        

    IF (TEMP_CLAS_COD  = 0)   
        THEN RAISE CLAS_COD_ERROR;
    ELSIF (TEMP_CLAS_FK <> 0  )
        THEN RAISE CLAS_DEL_ERROR;
    END IF; 

    -- DELETE
    DELETE
      FROM CLASSROOM_REGISTER
     WHERE CLASSROOM_CODE = V_CLAS_COD;      

    EXCEPTION       
        WHEN CLAS_COD_ERROR
            THEN RAISE_APPLICATION_ERROR(-20203, '유효한 강의실이 아닙니다.');
            ROLLBACK;           
        WHEN CLAS_DEL_ERROR 
            THEN RAISE_APPLICATION_ERROR(-20205, '해당 강의실은 참조되고 있으므로 삭제가 불가능합니다.');
            ROLLBACK;        
        WHEN OTHERS
            THEN ROLLBACK;         
    COMMIT;
END;

-- *30
CREATE OR REPLACE PROCEDURE PRC_OP_SUB_INSERT
(V_OP_COURSE_CODE   IN COURSE_OPEN.OP_COURSE_CODE%TYPE     --과정개설코드
,V_SUBJECT_CODE     IN SUBJECT.SUBJECT_CODE%TYPE           --과목코드
,V_START_DATE       IN SUBJECT_OPEN.START_DATE%TYPE        --시작날짜
,V_END_DATE         IN SUBJECT_OPEN.END_DATE%TYPE          --종료날짜
,V_TEXTBOOK_CODE    IN TEXTBOOK.TEXTBOOK_CODE%TYPE         --교재코드
,V_TEACHER_CODE     IN TEACHER_REGISTER.TEACHER_CODE%TYPE  --교수코드
)
IS
    --주요 변수 선언
    V_OP_SUBJECT_CODE    SUBJECT_OPEN.OP_SUBJECT_CODE%TYPE; --과목개설코드 OSC1 OSC2 OSC3...
    
    V_TCCODE    TEACHER_REGISTER.TEACHER_CODE%TYPE; -- 과정의 교수담는 변수
    
    V_SUB_COUNT  NUMBER;  -- 과정안에 과목 몇개있는지 세는 변수.
    V_COU_SDATE COURSE_OPEN.START_DATE%TYPE;    --과정시작날짜
    V_COU_EDATE COURSE_OPEN.END_DATE%TYPE;      --과정종료날짜
    V_SUB_EDATE SUBJECT_OPEN.END_DATE%TYPE;     --과목종료날짜
    
    USER_DEFINE_ERROR1  EXCEPTION;  -- 20303, '담당 교수가 배정되지 않은 과목입니다.'                       
    USER_DEFINE_ERROR2  EXCEPTION;  -- 20304, '입력정보의 교수와 해당과정의 교수가 일치하지 않습니다.'
    USER_DEFINE_ERROR3  EXCEPTION;  -- 20305,'과목기간이 과정기간에 포함되지 않습니다.'
    USER_DEFINE_ERROR4  EXCEPTION;  -- 20306,'과목기간이 중복됩니다. 다시 확인해주세요'
BEGIN  
    -- 해당 과정의 교수코드를 받아서 변수값에 담는다.
    SELECT TEACHER_CODE INTO V_TCCODE
    FROM COURSE_OPEN
    WHERE OP_COURSE_CODE = V_OP_COURSE_CODE;
   
    -- 교수코드가 NULL 이면 에러발생.
    IF (V_TCCODE IS NULL)
    THEN RAISE USER_DEFINE_ERROR1;
    -- 교수코드가 개설과정의 교수코드와 다르면 에러발생.
    ELSIF (V_TEACHER_CODE != V_TCCODE)
    THEN RAISE USER_DEFINE_ERROR2;
    END IF;
    
    -- 1. 과정시작날짜, 종료날짜 변수값 담기.
    SELECT START_DATE, END_DATE INTO V_COU_SDATE, V_COU_EDATE
    FROM COURSE_OPEN
    WHERE OP_COURSE_CODE = V_OP_COURSE_CODE;
    
    -- 에러발생경우
    IF (V_COU_SDATE - V_START_DATE > 0 OR V_END_DATE - V_COU_EDATE > 0)
    THEN RAISE USER_DEFINE_ERROR3;
    END IF;
      
    SELECT MAX(END_DATE) INTO V_SUB_EDATE
    FROM SUBJECT_OPEN
    WHERE OP_COURSE_CODE = V_OP_COURSE_CODE;
    
    IF (V_SUB_EDATE IS NOT NULL AND (V_SUB_EDATE - V_START_DATE > 0))
    THEN RAISE USER_DEFINE_ERROR4;
    END IF;

   
    -- 과목개설코드에 값 담아내기
    SELECT NVL(MAX(TO_NUMBER(SUBSTR(OP_SUBJECT_CODE,3))),0) + 1 INTO V_OP_SUBJECT_CODE
    FROM SUBJECT_OPEN;
    
    V_OP_SUBJECT_CODE := 'OSC' || V_OP_SUBJECT_CODE;
    
    
    -- INSERT 쿼리문
    INSERT INTO SUBJECT_OPEN
    (OP_SUBJECT_CODE, SUBJECT_CODE, TEXTBOOK_CODE, OP_COURSE_CODE, START_DATE, END_DATE)
    VALUES(V_OP_SUBJECT_CODE, V_SUBJECT_CODE, V_TEXTBOOK_CODE, V_OP_COURSE_CODE, TO_DATE(V_START_DATE,'YYYY-MM-DD') ,TO_DATE(V_END_DATE,'YYYY-MM-DD') );

    --예외처리
    EXCEPTION
        WHEN USER_DEFINE_ERROR1
        THEN RAISE_APPLICATION_ERROR(-20303, '담당 교수가 배정되지 않은 과목입니다.');
        ROLLBACK;
        WHEN USER_DEFINE_ERROR2
        THEN RAISE_APPLICATION_ERROR(-20304, '입력정보의 교수와 해당과정의 교수가 일치하지 않습니다.');
        ROLLBACK;
        WHEN USER_DEFINE_ERROR3
        THEN RAISE_APPLICATION_ERROR(-20305,'과목기간이 과정기간에 포함되지 않습니다.');
        ROLLBACK;
        WHEN USER_DEFINE_ERROR4
        THEN RAISE_APPLICATION_ERROR(-20306,'과목기간이 중복됩니다. 다시 확인해주세요');
        ROLLBACK;
    --커밋
    COMMIT;
END;

-- *31
--○ 관리자가 과목정보를 출력하는 프로시저 PRC_SUB_OP_SELECT(과목코드)
CREATE OR REPLACE PROCEDURE PRC_SUB_OP_SELECT
(V_CODE     IN MANAGER_REGISTER.MANAGER_CODE%TYPE
)
IS  
    -- 커서 데이터 담는 변수 선언
    V_CNAME     COURSE.COURSE_NAME%TYPE;        --과정명
    V_CLANAME   CLASSROOM_REGISTER.CLASSROOM_NAME%TYPE; -- 강의실명
    V_SUB_NAME  SUBJECT.SUBJECT_NAME%TYPE;      --과목명
    V_SDATE     SUBJECT_OPEN.START_DATE%TYPE;   --과목시작날짜
    V_EDATE     SUBJECT_OPEN.END_DATE%TYPE;     --과목종료날짜
    V_TEXTBOOK  TEXTBOOK.TEXTBOOK_NAME%TYPE;    --교재명
    V_TC_NAME   TEACHER_REGISTER.NAME%TYPE;     --교수명
    
    -- 커서 정의
    CURSOR CUR_SUB_OP_SELECT
    IS
    SELECT T2.과정명, T2.강의실명, T1.과목명
       ,T1.과목시작날짜,T1.과목종료날짜
       ,T1.교재명, T2.교수자명
    FROM
    (
        SELECT SO.START_DATE "과목시작날짜"
               ,SO.END_DATE "과목종료날짜"
               ,S.SUBJECT_NAME "과목명"
               ,T.TEXTBOOK_NAME "교재명"
               ,SO.OP_COURSE_CODE "과정개설코드"
        FROM SUBJECT_OPEN SO JOIN SUBJECT S
        ON SO.SUBJECT_CODE = s.SUBJECT_CODE JOIN TEXTBOOK T
        ON SO.TEXTBOOK_CODE = T.TEXTBOOK_CODE
    )T1 JOIN
    (
        SELECT C.COURSE_NAME "과정명"
               ,CR.CLASSROOM_NAME "강의실명"
               ,CO.OP_COURSE_CODE "과정개설코드"
               ,TR.NAME "교수자명"
        FROM COURSE_OPEN CO JOIN COURSE C 
        ON CO.COURSE_CODE = C.COURSE_CODE JOIN CLASSROOM_REGISTER CR 
        ON CO.CLASSROOM_CODE = CR.CLASSROOM_CODE JOIN TEACHER_REGISTER TR
        ON CO.TEACHER_CODE = TR.TEACHER_CODE
    )T2
    ON T1.과정개설코드 = T2.과정개설코드;
    
    --등록된 관리자인지 판단하는 임시변수 선언
    V_TEMP  NUMBER; 
  
    -- 사용자 에러변수 선언 
    USER_DEFINE_ERROR1   EXCEPTION;  -- 20102,'관리자가 아닙니다. 교수정보출력은 관리자만 가능합니다'
    USER_DEFINE_ERROR2   EXCEPTION;  -- 20103,'등록된 관리자가 아닙니다.'

BEGIN
    -- 임시변수에 값 담기
    SELECT COUNT(*) INTO V_TEMP
    FROM MANAGER_REGISTER
    WHERE MANAGER_CODE = V_CODE;
    
    -- 관리자인지 확인. 관리자가 아니면 에러 발생.
    IF (SUBSTR(V_CODE,1,1) != 'M')
    THEN RAISE USER_DEFINE_ERROR1;
    -- 등록된 관리자가 아니면 에러 발생
    ELSIF (V_TEMP = 0)
    THEN RAISE USER_DEFINE_ERROR2;
    END IF;
    
    -- 커서 오픈
    OPEN CUR_SUB_OP_SELECT;
    
    LOOP
        FETCH CUR_SUB_OP_SELECT INTO V_CNAME,V_CLANAME,V_SUB_NAME,V_SDATE,V_EDATE,V_TEXTBOOK,V_TC_NAME ;
        
        EXIT WHEN CUR_SUB_OP_SELECT%NOTFOUND;

    END LOOP;
    
    -- 커서 클로즈
    CLOSE CUR_SUB_OP_SELECT;

    
    -- 예외처리
    EXCEPTION
    WHEN USER_DEFINE_ERROR1
    THEN RAISE_APPLICATION_ERROR(-20102, '관리자가 아닙니다. 교수정보출력은 관리자만 가능합니다.');
    ROLLBACK;
    WHEN USER_DEFINE_ERROR2
    THEN RAISE_APPLICATION_ERROR(-20103,'등록된 관리자가 아닙니다.');
    ROLLBACK;
    
    --커밋
    COMMIT;
END;

-- *32
--○ 관리자의 학생 정보 추가 프로시저 PRC_STD_INSERT
CREATE OR REPLACE PROCEDURE PRC_STD_INSERT
(   V_NAME  IN STUDENT_REGISTER.NAME%TYPE
,   V_SSN   IN STUDENT_REGISTER.SSN%TYPE
)
IS
    V_STUDENT_CODE   STUDENT_REGISTER.STUDENT_CODE%TYPE;
BEGIN
    SELECT NVL(MAX(TO_NUMBER(SUBSTR(STUDENT_CODE, 2))), 0) + 1 INTO V_STUDENT_CODE
    FROM STUDENT_REGISTER;
    
    V_STUDENT_CODE := 'S' || LPAD(TO_CHAR(V_STUDENT_CODE),4,0);
    
    INSERT INTO STUDENT_REGISTER(NAME, SSN, STUDENT_CODE, PASSWORD)
    VALUES(V_NAME, V_SSN , V_STUDENT_CODE, SUBSTR(V_SSN,7));

    COMMIT;
END;


-- *34
--○ 관리자의 학생정보 수정 프로시저 PRC_STU_REG_MANEDIT
CREATE OR REPLACE PROCEDURE PRC_STU_REG_MANEDIT
(V_STD_COD      IN STUDENT_REGISTER.STUDENT_CODE%TYPE  --(학생코드)
,V_PW           IN STUDENT_REGISTER.PASSWORD%TYPE      --(비밀번호)
,V_NAME         IN STUDENT_REGISTER.NAME%TYPE          --(학생명)
,V_SSN          IN STUDENT_REGISTER.SSN%TYPE           --(주민번호)
,V_REG_DATE     IN STUDENT_REGISTER.REGISTER_DATE%TYPE --(가입일자)
)
IS    
    STD_COD_ERROR   EXCEPTION;
BEGIN     
    IF SQL%NOTFOUND
        THEN RAISE STD_COD_ERROR;
    END IF;
    
    --UPDATE
    UPDATE STUDENT_REGISTER
    SET PASSWORD = V_PW,  NAME =  V_NAME  , SSN = V_SSN
    , REGISTER_DATE = V_REG_DATE
    WHERE STUDENT_CODE = V_STD_COD;
    
    EXCEPTION
        WHEN STD_COD_ERROR
            THEN RAISE_APPLICATION_ERROR(-20104, '유효한 회원이 아닙니다.');
                ROLLBACK;
        WHEN OTHERS
            THEN ROLLBACK;
        
    COMMIT;
END;

-- *36
--○ 중도탈락코드 시퀀스 생성
CREATE SEQUENCE DR_STD_SEQ
START WITH 1
INCREMENT BY 1
MINVALUE 1;


-- *37
--○ 중도탈락 학생 입력 프로시저 PRC_DR_STD_INSERT
CREATE OR REPLACE PROCEDURE PRC_DR_STD_INSERT
( V_STUDENT_CODE        IN  STUDENT_REGISTER.STUDENT_CODE%TYPE
, V_REG_COURSE_CODE     IN  COURSE_REGISTER.REG_COURSE_CODE%TYPE
, V_DROP_DATE           IN  STUDENT_DROP.DROP_DATE%TYPE
, V_DR_REASON_CODE      IN  DROP_REASON.DR_REASON_CODE%TYPE
, V_DETAIL              IN  DROP_REASON.DETAIL%TYPE
)
IS 
    T_STUDENT_CODE          STUDENT_REGISTER.STUDENT_CODE%TYPE;
    T_REG_COURSE_CODE       COURSE_REGISTER.REG_COURSE_CODE%TYPE;
    T_DR_REASON_CODE        DROP_REASON.DR_REASON_CODE%TYPE;
    T_DROP_CODE             STUDENT_DROP.DROP_CODE%TYPE;    
    
    PK_NUMBER               NUMBER;
        
    USER_DEFINE_ERROR1       EXCEPTION;
    USER_DEFINE_ERROR2       EXCEPTION;
BEGIN
    -- 수강신청된 학생인지 조회
    -- 수강신청을 안 한 학생일 경우 NO_DATA_FOUND 발생
    SELECT STUDENT_CODE, REG_COURSE_CODE INTO T_STUDENT_CODE, T_REG_COURSE_CODE
    FROM COURSE_REGISTER
    WHERE STUDENT_CODE = V_STUDENT_CODE
      AND REG_COURSE_CODE = V_REG_COURSE_CODE;
    
    -- 이미 중도 탈락 테이블에 있는 학생인지 조회
    SELECT T.DROP_CODE INTO T_DROP_CODE
    FROM 
    (
        SELECT DROP_CODE
        FROM STUDENT_DROP
        WHERE REG_COURSE_CODE = T_REG_COURSE_CODE
    ) T RIGHT OUTER JOIN DUAL
    ON 1=1;
    
    IF (T_DROP_CODE IS NOT NULL)
        THEN RAISE USER_DEFINE_ERROR1;
    END IF;
    
    -- DR_REASON_CODE가 없으면 NULL값을 반환함.
    SELECT T.DR_REASON_CODE INTO T_DR_REASON_CODE
    FROM
    (
        SELECT DR_REASON_CODE
        FROM DROP_REASON
        WHERE DR_REASON_CODE = V_DR_REASON_CODE
    ) T RIGHT OUTER JOIN DUAL
    ON 1=1;
    
    -- 0번일 경우 중도탈락 사유를 새로 입력한다.
    IF (V_DR_REASON_CODE = 0)
        THEN SELECT NVL(MAX(DR_REASON_CODE), 0) INTO PK_NUMBER
             FROM DROP_REASON;
             
             INSERT INTO DROP_REASON (DR_REASON_CODE, DETAIL)
             VALUES (PK_NUMBER+1, V_DETAIL);
    
    -- 존재하지 않는 중도탈락 사유 번호를 접근했다. (에러)
    ELSIF ( T_DR_REASON_CODE IS NULL)
        THEN RAISE USER_DEFINE_ERROR2;
    
    -- 둘다 아니면 정상적인 접근이므로 중도탈락사유코드(PK) 가져옴.
    ELSE
        SELECT DR_REASON_CODE INTO PK_NUMBER
        FROM DROP_REASON
        WHERE DR_REASON_CODE = T_DR_REASON_CODE;
    END IF;
    
    -- 시퀀스 쓸 경우
    -- DROP_STUDENT 테이블에 데이터 입력
    INSERT INTO STUDENT_DROP(DROP_CODE, REG_COURSE_CODE, DR_REASON_CODE, DROP_DATE)
    VALUES(CONCAT('D', TO_CHAR(DR_STD_SEQ.NEXTVAL)), T_REG_COURSE_CODE, PK_NUMBER, V_DROP_DATE);
 
    
    EXCEPTION
        WHEN NO_DATA_FOUND
            THEN RAISE_APPLICATION_ERROR(-20701,'해당 학생의 수강신청 내역이 없습니다.');
                ROLLBACK;
        WHEN USER_DEFINE_ERROR1
            THEN RAISE_APPLICATION_ERROR(-20602, '중도탈락이 등록된 학생입니다.');
                ROLLBACK;
        WHEN USER_DEFINE_ERROR2
            THEN RAISE_APPLICATION_ERROR(-20601, '존재하지 않는 중도탈락 사유입니다.');
                ROLLBACK;
        WHEN OTHERS
            THEN ROLLBACK;
    -- 커밋
    COMMIT;
END;


-- *38
-- ○ 중도탈락 수정 프로시저 PRC_DR_RE_UPDATE(중도탈락사유코드, 중도상세사유)
CREATE OR REPLACE PROCEDURE PRC_DR_RE_UPDATE
( V_DR_REASON_CODE      IN  DROP_REASON.DR_REASON_CODE%TYPE
, V_DETAIL              IN  DROP_REASON.DETAIL%TYPE
)
IS
BEGIN
   
    -- 존재하지 않는 값일 경우 UPDATE 되지 않음.
    UPDATE DROP_REASON
    SET DETAIL = V_DETAIL
    WHERE DR_REASON_CODE = V_DR_REASON_CODE;
    
    EXCEPTION
        WHEN OTHERS
            THEN ROLLBACK;
            
    COMMIT;
END;


-- *39
--○ 중도탈락데이터 수정 프로시저 PRC_DR_STD_UPDATE(중도탈락코드, 중도탈락일자)
CREATE OR REPLACE PROCEDURE PRC_DR_STD_UPDATE
( V_DROP_CODE           IN  STUDENT_DROP.DROP_CODE%TYPE
, V_DROP_DATE           IN  STUDENT_DROP.DROP_DATE%TYPE)
IS
-- 중도탈락일자 UPDATE
BEGIN
    UPDATE STUDENT_DROP
    SET DROP_DATE = V_DROP_DATE
    WHERE DROP_CODE = V_DROP_CODE;
    
    EXCEPTION
        WHEN OTHERS
            THEN ROLLBACK;    
    COMMIT;
END;


-- *41
--○ 중도탈락 삭제 프로시저 PRC_DR_STD_DELETE
CREATE OR REPLACE PROCEDURE PRC_DR_STD_DELETE
( V_STUDENT_CODE        IN  STUDENT_REGISTER.STUDENT_CODE%TYPE
, V_REG_COURSE_CODE     IN  COURSE_REGISTER.REG_COURSE_CODE%TYPE
)
IS
    T_DROP_CODE             STUDENT_DROP.DROP_CODE%TYPE;
   
    USER_DEFINE_ERROR       EXCEPTION;
BEGIN
-- 이미 중도 탈락 테이블에 있는 학생인지 조회
    SELECT T.DROP_CODE INTO T_DROP_CODE
    FROM 
    (
        SELECT DROP_CODE
        FROM STUDENT_DROP
        WHERE REG_COURSE_CODE = V_REG_COURSE_CODE
    ) T RIGHT OUTER JOIN DUAL
    ON 1=1;
    
-- 중도탈락학생이라면 중도탈락코드 삭제
    IF (T_DROP_CODE IS NOT NULL) 
        -- 중도탈락코드를 삭제하기      
        THEN DELETE 
             FROM STUDENT_DROP 
             WHERE DROP_CODE = T_DROP_CODE; 
    ELSE
        RAISE USER_DEFINE_ERROR;
    END IF;
    
    EXCEPTION
        WHEN USER_DEFINE_ERROR
                THEN RAISE_APPLICATION_ERROR(-20603, '중도탈락이 등록되지 않아 삭제할 수 없습니다.');
                    ROLLBACK;
        WHEN OTHERS
            THEN ROLLBACK;
    -- 커밋
    COMMIT;
END;




--------------------------------------------------------------------------------
-- *7
-- [교수자]
--○ 교수자 데이터 추가 프로시저 PRC_TC_INSERT(이름, 주민번호)
CREATE OR REPLACE PROCEDURE PRC_TC_INSERT
(V_NAME IN TEACHER_REGISTER.NAME%TYPE
,V_SSN  IN TEACHER_REGISTER.SSN%TYPE
)
IS
    V_TEACHER_CODE  TEACHER_REGISTER.TEACHER_CODE%TYPE; --T0001부터 시작.       
    V_PASSWORD      TEACHER_REGISTER.PASSWORD%TYPE;
BEGIN
    SELECT NVL(MAX(TO_NUMBER(SUBSTR(TEACHER_CODE,2))),0)  + 1 INTO V_TEACHER_CODE
    FROM TEACHER_REGISTER;
    
    V_TEACHER_CODE := 'T' || LPAD(TO_CHAR(V_TEACHER_CODE),4,0);
    
    V_PASSWORD := SUBSTR(V_SSN,7);
    
   INSERT INTO  TEACHER_REGISTER(TEACHER_CODE,PASSWORD,NAME,SSN)
   VALUES(V_TEACHER_CODE,V_PASSWORD, V_NAME, V_SSN);
END;


-- *31
--○ 교수자가 교수정보 수정 프로시저 TEACHER_REGISTER_TC_UPDATE
CREATE OR REPLACE PROCEDURE TEACHER_REGISTER_TC_UPDATE
( V_TC_COD        IN TEACHER_REGISTER.TEACHER_CODE%TYPE
, V_PW            IN TEACHER_REGISTER.PASSWORD%TYPE
, V_NEW_PW        IN TEACHER_REGISTER.PASSWORD%TYPE
, V_NAME          IN TEACHER_REGISTER.NAME%TYPE
, V_SSN           IN TEACHER_REGISTER.SSN%TYPE
)
IS
    TEMP_TC_COD     NUMBER;
    TEMP_PW         NUMBER;
    
    TC_COD_ERROR    EXCEPTION;
    PW_ERROR        EXCEPTION;
BEGIN
    SELECT COUNT(*) INTO TEMP_TC_COD
      FROM TEACHER_REGISTER
     WHERE TEACHER_CODE = V_TC_COD;
    
    SELECT COUNT(*) INTO TEMP_PW
      FROM TEACHER_REGISTER
     WHERE TEACHER_CODE = V_TC_COD
       AND PASSWORD = V_PW;
    
    IF(TEMP_TC_COD = 0)
        THEN RAISE TC_COD_ERROR;
    ELSIF (TEMP_PW = 0)
        THEN RAISE PW_ERROR;
    END IF;
    
    UPDATE TEACHER_REGISTER
       SET PASSWORD = V_NEW_PW, NAME = V_NAME, SSN = V_SSN
     WHERE TEACHER_CODE = V_TC_COD;

    EXCEPTION
        WHEN TC_COD_ERROR
            THEN RAISE_APPLICATION_ERROR(-20202, '유효한 교수가 아닙니다.');
            ROLLBACK;
        WHEN PW_ERROR
            THEN RAISE_APPLICATION_ERROR(-20103, '아이디, 비밀번호가 일치하지 않습니다');
            ROLLBACK;
        WHEN OTHERS
            THEN ROLLBACK;
    COMMIT;
END;

-- *5
--○ 교수자 비밀번호변경 프로시저 PRC_TC_PW_CHANGE(ID,PW,NEWPW)
CREATE OR REPLACE PROCEDURE PRC_TC_PW_CHANGE
( V_CODE  IN TEACHER_REGISTER.TEACHER_CODE%TYPE
, V_PW    IN TEACHER_REGISTER.PASSWORD%TYPE
, V_NEWPW IN TEACHER_REGISTER.PASSWORD%TYPE)
IS
    V_PW2 TEACHER_REGISTER.PASSWORD%TYPE;
    USER_DEFINE_ERROR EXCEPTION;
BEGIN
    
    SELECT PASSWORD INTO V_PW2
    FROM TEACHER_REGISTER
    WHERE TEACHER_CODE = V_CODE;
    
    IF (V_PW = V_PW2)
        THEN UPDATE TEACHER_REGISTER
             SET PASSWORD = V_NEWPW
             WHERE TEACHER_CODE = V_CODE;
    ELSE
        RAISE USER_DEFINE_ERROR;
    END IF;
    
    -- 커밋
    COMMIT;
    
    EXCEPTION
       WHEN USER_DEFINE_ERROR
            THEN RAISE_APPLICATION_ERROR(-20103, '아이디, 비밀번호가 일치하지 않습니다.');
            ROLLBACK;
END;

-- *42
-- 성적 입력 프로시저 PRC_IN_SCR_INSERT
CREATE OR REPLACE PROCEDURE PRC_IN_SCR_INSERT
( V_ATTENDANCE_SCORE     IN SCORE_INPUT.ATTENDANCE_SCORE%TYPE
, V_WRITING_SCORE        IN SCORE_INPUT.WRITING_SCORE%TYPE
, V_PERFORMANCE_SCORE    IN SCORE_INPUT.PERFORMANCE_SCORE%TYPE
, V_OP_SUBJECT_CODE      IN SUBJECT_OPEN.OP_SUBJECT_CODE%TYPE
, V_STUDENT_CODE         IN STUDENT_REGISTER.STUDENT_CODE%TYPE
)
IS
    V_OP_COURSE_CODE    COURSE_OPEN.OP_COURSE_CODE%TYPE;
    V_REG_COURSE_CODE   COURSE_REGISTER.REG_COURSE_CODE%TYPE;
    
    V_DROP_CODE         STUDENT_DROP.DROP_CODE%TYPE;
    
    V_START_DATE        SUBJECT_OPEN.START_DATE%TYPE;
    V_END_DATE          SUBJECT_OPEN.END_DATE%TYPE;
    V_DROP_DATE         STUDENT_DROP.DROP_DATE%TYPE;
    V_SYSDATE           DATE;
    
    V_SERIAL_CODE       SCORE_INPUT.SCORE_CODE%TYPE;
    V_SCORE_CODE        SCORE_INPUT.SCORE_CODE%TYPE;
     
    USER_DEFINE_ERROR1   EXCEPTION;
    USER_DEFINE_ERROR2   EXCEPTION;
    USER_DEFINE_ERROR3   EXCEPTION;
    USER_DEFINE_ERROR4   EXCEPTION;
BEGIN
    -- REG_COURSE_CODE 얻기 위한 과정 1
    SELECT OP_COURSE_CODE INTO V_OP_COURSE_CODE
    FROM SUBJECT_OPEN
    WHERE OP_SUBJECT_CODE = V_OP_SUBJECT_CODE;
        
    --REG_COURSE_CODE 얻기 위한 과정 2
    -- RIGHT OUTHER JOIN DUAL을 하는 이유
    -- ROW 조회결과가 없을 경우 NULL이 아니라 아예 없는 값
    -- 따라서 NULL 출력을 위해서 DUAL과 RIGHT OUTER JOIN을 함
    SELECT T.REG_COURSE_CODE INTO V_REG_COURSE_CODE
    FROM
    ( 
        SELECT REG_COURSE_CODE
        FROM COURSE_REGISTER
        WHERE STUDENT_CODE = V_STUDENT_CODE AND OP_COURSE_CODE = V_OP_COURSE_CODE
    ) T RIGHT OUTER JOIN DUAL
    ON 1=1;
        
    -- 학생이 수강신청을 했는지 안했는지 검사
    IF (V_REG_COURSE_CODE IS NULL)
        THEN RAISE USER_DEFINE_ERROR1;
    END IF;
    
    -- 이미 성적 입력한 적이 있는지 검사
    SELECT T.SCORE_CODE INTO V_SCORE_CODE    
    FROM
    (
        SELECT SCORE_CODE
        FROM SCORE_INPUT
        WHERE REG_COURSE_CODE = V_REG_COURSE_CODE AND OP_SUBJECT_CODE = V_OP_SUBJECT_CODE
    ) T RIGHT OUTER JOIN DUAL
    ON 1=1;
    
    -- 성적이 이미 존재하면 PRC_IN_SCR_UPDATE2 로 보냄. 
    IF ( V_SCORE_CODE IS NOT NULL )
        THEN RAISE USER_DEFINE_ERROR4;
    END IF;
    
    -- 중도탈락여부를 확인하기 위한 코드. 중도탈락 시점도 포함
    -- DROP을 안 했을 경우 NULL값 부여
    SELECT T.DROP_CODE, T.DROP_DATE INTO V_DROP_CODE, V_DROP_DATE
    FROM
    (
        SELECT DROP_CODE, DROP_DATE 
        FROM STUDENT_DROP
        WHERE REG_COURSE_CODE = V_REG_COURSE_CODE
    ) T RIGHT OUTER JOIN DUAL
    ON 1=1;
        
    -- 해당 과목 기간 추출
    SELECT START_DATE, END_DATE INTO V_START_DATE, V_END_DATE
    FROM SUBJECT_OPEN
    WHERE OP_SUBJECT_CODE = V_OP_SUBJECT_CODE;
       
    -- DROP_CODE(중도탈락코드)가 있으면 중도탈락
    IF ( V_DROP_CODE IS NOT NULL )
            -- 중도탈락시점이 강의 끝나는 시점보다 빠른 경우. 안 들은 수업.
        THEN IF( V_END_DATE > V_DROP_DATE)
                THEN RAISE USER_DEFINE_ERROR2;
             END IF;       
    END IF;
     
    -- 성적 입력시점이 강의 시작 전이라면 불가능
    SELECT SYSDATE INTO V_SYSDATE
    FROM DUAL;
        
    IF (SYSDATE < V_START_DATE)
        THEN RAISE USER_DEFINE_ERROR3;
    END IF;
    
    -- 성적코드 = 과목코드_시리얼넘버
    -- EX) S007_0001  *시리얼넘버: 연속된 오름차순 숫자
    -- 현재 더미데이터의 경우 C1S1_001 사용중
    -- 3자리 시리얼 넘버 생성
    
    SELECT TO_CHAR(NVL(MAX(TO_NUMBER(SUBSTR(SCORE_CODE, 6))), 0)+1) INTO V_SERIAL_CODE
    FROM SCORE_INPUT
    WHERE OP_SUBJECT_CODE = V_OP_SUBJECT_CODE;
       
    -- 성적입력코드(PK) 생성
    SELECT (V_OP_SUBJECT_CODE || '_' || V_SERIAL_CODE) INTO V_SCORE_CODE
    FROM DUAL;
    
    --입력
    INSERT INTO SCORE_INPUT (SCORE_CODE, OP_SUBJECT_CODE, REG_COURSE_CODE, ATTENDANCE_SCORE, WRITING_SCORE, PERFORMANCE_SCORE)
    VALUES(V_SCORE_CODE, V_OP_SUBJECT_CODE, V_REG_COURSE_CODE, V_ATTENDANCE_SCORE, V_WRITING_SCORE, V_PERFORMANCE_SCORE);  
    
    COMMIT;

    -- 예외
    EXCEPTION
        WHEN USER_DEFINE_ERROR1 
            THEN RAISE_APPLICATION_ERROR(-20701, '해당 학생의 수강신청 내역이 없습니다.');
                ROLLBACK;
        WHEN USER_DEFINE_ERROR2 
            THEN RAISE_APPLICATION_ERROR(-20600, '중도 탈락으로 성적입력 대상에서 제외됩니다');
                ROLLBACK;
        WHEN USER_DEFINE_ERROR3 
            THEN RAISE_APPLICATION_ERROR(-20602, '강의예정으로 성적 입력이 불가능합니다.');
                ROLLBACK;
        -- 이미 값이 존재하는 경우 PRC_IN_SCR_UPDATE2(업데이트 프로시저)로 보냄.
        WHEN USER_DEFINE_ERROR4
            THEN PRC_IN_SCR_UPDATE2(V_ATTENDANCE_SCORE, V_WRITING_SCORE, V_PERFORMANCE_SCORE
                                   , V_SCORE_CODE, V_REG_COURSE_CODE);
        WHEN OTHERS
            THEN ROLLBACK;
END;

-- *43
-- 배점 정보 수정 프로시저
CREATE OR REPLACE PROCEDURE PRC_OP_SUB_UPDATE_RATE
( V_OP_SUBJECT_CODE     IN SUBJECT_OPEN.OP_SUBJECT_CODE%TYPE
, V_ATTENDANCE_RATE     IN SUBJECT_OPEN.ATTENDANCE_RATE%TYPE
, V_WRITING_RATE         IN SUBJECT_OPEN.WRITING_RATE%TYPE
, V_PERFORMANCE_RATE    IN SUBJECT_OPEN.PERFORMANCE_RATE%TYPE
)
IS
    TEST_OP_SUBJECT_CODE   SUBJECT_OPEN.OP_SUBJECT_CODE%TYPE;
    
    USER_DEFINE_ERROR EXCEPTION;
BEGIN
    -- 데이터가 조회되지 않는 경우 NO_DATA_FOUND 발생
    SELECT OP_SUBJECT_CODE INTO TEST_OP_SUBJECT_CODE
    FROM SUBJECT_OPEN
    WHERE OP_SUBJECT_CODE = V_OP_SUBJECT_CODE;
    
    IF (V_WRITING_RATE + V_ATTENDANCE_RATE + V_PERFORMANCE_RATE != 100)
        THEN RAISE USER_DEFINE_ERROR;
    END IF;
    
    UPDATE SUBJECT_OPEN
    SET WRITING_RATE = V_WRITING_RATE
      , ATTENDANCE_RATE = V_ATTENDANCE_RATE
      , PERFORMANCE_RATE = V_PERFORMANCE_RATE
    WHERE OP_SUBJECT_CODE = V_OP_SUBJECT_CODE;
    
    EXCEPTION
        WHEN NO_DATA_FOUND
            THEN RAISE_APPLICATION_ERROR(-20300, '유효한 과목이 아닙니다.');
                ROLLBACK;
        WHEN USER_DEFINE_ERROR
            THEN RAISE_APPLICATION_ERROR(-20400, '총 배점은 100점입니다. 다시 입력해주세요');
                ROLLBACK;
        WHEN OTHERS
            THEN ROLLBACK;
    
    --커밋
    COMMIT;
END;

-- *44
-- 과목과 전담강사 일치하는지 확인 후, 그 과목에 대한 전체 학생 성적 출력하는 프로시저
CREATE OR REPLACE PROCEDURE PRC_PRINT_SUBJECT_GRADE
( V_OP_SUBJECT_CODE     IN SUBJECT_OPEN.OP_SUBJECT_CODE%TYPE
, V_TEACHER_CODE        IN TEACHER_REGISTER.TEACHER_CODE%TYPE
)
IS
    -- 에러 체크 도와주는 변수
    V_TEACHER_IS_NULL_CHECK      TEACHER_REGISTER.TEACHER_CODE%TYPE;
    V_TEACHER_EXIST             NUMBER;
    
    USER_DEFINE_ERROR1          EXCEPTION;
    USER_DEFINE_ERROR2          EXCEPTION;
    USER_DEFINE_ERROR3          EXCEPTION;
    
    -- 커서
    V_CURSOR                    SYS_REFCURSOR;
    
    V_ROWCOUNT                  NUMBER;
    
    -- 이 밑으로 선언된 것 모두 커서용 변수
    V_SUBJECT_NAME              SUBJECT.SUBJECT_NAME%TYPE;
    V_START_DATE                SUBJECT_OPEN.START_DATE%TYPE;
    V_END_DATE                  SUBJECT_OPEN.END_DATE%TYPE;
    V_TEXTBOOK_NAME             TEXTBOOK.TEXTBOOK_NAME%TYPE;
    V_NAME                      STUDENT_REGISTER.NAME%TYPE;
    V_ATTENDANCE_SCORE          SCORE_INPUT.ATTENDANCE_SCORE%TYPE;
    V_WRITING_SCORE             SCORE_INPUT.WRITING_SCORE%TYPE;
    V_PERFORMANCE_SCORE         SCORE_INPUT.PERFORMANCE_SCORE%TYPE;
    V_ATTENDANCE_SCORE_RATE     SCORE_INPUT.ATTENDANCE_SCORE%TYPE;
    V_WRITING_SCORE_RATE        SCORE_INPUT.WRITING_SCORE%TYPE;
    V_PERFORMANCE_SCORE_RATE    SCORE_INPUT.PERFORMANCE_SCORE%TYPE;
    V_TOTAL                     NUMBER;
    V_RANK                      NUMBER;
    V_DROP                      VARCHAR2(20);
BEGIN
    -- 일단 이 과목에 전담 강사가 있는지 검사. 강사가 NULL인 경우가 있기 때문.    
    SELECT CO.TEACHER_CODE INTO V_TEACHER_IS_NULL_CHECK
    FROM SUBJECT_OPEN SO, COURSE_OPEN CO
    WHERE SO.OP_COURSE_CODE = CO.OP_COURSE_CODE
      AND SO.OP_SUBJECT_CODE = V_OP_SUBJECT_CODE;
    
    IF (V_TEACHER_IS_NULL_CHECK IS NULL)
        THEN RAISE USER_DEFINE_ERROR1;
    END IF;
    
    SELECT COUNT(*) INTO V_TEACHER_EXIST
    FROM TEACHER_REGISTER
    WHERE TEACHER_CODE = V_TEACHER_CODE;
    
    IF (V_TEACHER_EXIST  = 0)
        THEN RAISE USER_DEFINE_ERROR3;
    END IF;
    
    -- 전담 강사와 과목이 일치하는지 검사
    IF (V_TEACHER_IS_NULL_CHECK != V_TEACHER_CODE)
        THEN RAISE USER_DEFINE_ERROR2;
    END IF;
    
    -- 커서 호출
    PRC_GRADE_CURSOR(V_OP_SUBJECT_CODE, V_CURSOR);
    
    -- 호출한 커서 이용해서 성적값 출력
    
    DBMS_OUTPUT.PUT_LINE( ' 과목명 ' || '   ' || ' 시작 날짜 ' || '   ' || '종료 날짜 '
                            || '   ' || '교재명 ' || '   ' || '학생명 ' || '   ' || '출결점수'
                            || '   ' || '필기점수' || '   ' || '실기점수'
                            || '   ' || '출결(배점)' || '   ' || '필기(배점)'
                            || '   ' || '실기(배점)' || '   ' || '총합' || '   ' || '등수' || '   ' || '중도탈락여부');
    LOOP
        FETCH V_CURSOR INTO V_SUBJECT_NAME, V_START_DATE, V_END_DATE
                                  , V_TEXTBOOK_NAME, V_NAME, V_ATTENDANCE_SCORE
                                  , V_WRITING_SCORE, V_PERFORMANCE_SCORE
                                  , V_ATTENDANCE_SCORE_RATE, V_WRITING_SCORE_RATE
                                  , V_PERFORMANCE_SCORE_RATE, V_TOTAL, V_RANK, V_DROP;
        
        -- 데이터 출력이 없는 경우 감지.
        IF ( V_CURSOR%ROWCOUNT = 0 )
            THEN V_ROWCOUNT := V_CURSOR%ROWCOUNT;
        END IF;
        
        EXIT WHEN V_CURSOR%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE(V_SUBJECT_NAME || '   ' || V_START_DATE || '   ' || V_END_DATE
                            || '   ' || V_TEXTBOOK_NAME || '   ' || V_NAME || CHR(9) || CHR(9) || V_ATTENDANCE_SCORE
                            || CHR(9) || CHR(9) || '   ' || V_WRITING_SCORE || CHR(9) || CHR(9) || CHR(9) || V_PERFORMANCE_SCORE
                            || CHR(9) || CHR(9) || '   ' || V_ATTENDANCE_SCORE_RATE || CHR(9) || CHR(9) || '   ' 
                            || V_WRITING_SCORE_RATE || CHR(9) || CHR(9) || '   ' ||V_PERFORMANCE_SCORE_RATE 
                            || CHR(9) || CHR(9) || V_TOTAL || CHR(9) || CHR(9) || V_RANK 
                            || CHR(9) || CHR(9) || V_DROP);
    END LOOP;
    CLOSE V_CURSOR;
    
    IF ( V_ROWCOUNT = 0)
        THEN DBMS_OUTPUT.PUT_LINE('데이터 없음');
    END IF;
    
    EXCEPTION
        WHEN USER_DEFINE_ERROR1
            THEN RAISE_APPLICATION_ERROR(-20502, '해당 과목에 전담 교수가 없습니다.');
                ROLLBACK;
        WHEN USER_DEFINE_ERROR2
            THEN RAISE_APPLICATION_ERROR(-20501, '해당 교수가 전담하고 있는 과목이 아닙니다.');
                ROLLBACK;
        WHEN USER_DEFINE_ERROR3
            THEN RAISE_APPLICATION_ERROR(-20504, '교수가 존재하지 않습니다');
                ROLLBACK;
        WHEN NO_DATA_FOUND
            THEN RAISE_APPLICATION_ERROR(-20503, '과목이 존재하지 않습니다');
                ROLLBACK;
        WHEN OTHERS
            THEN ROLLBACK;
END;
-- *45
-- 과목에 대한 성적 출력을 위한 커서 호출 프로시저
CREATE OR REPLACE PROCEDURE PRC_GRADE_CURSOR
( V_OP_SUBJECT_CODE     IN SUBJECT_OPEN.OP_SUBJECT_CODE%TYPE
, V_CURSOR              IN OUT SYS_REFCURSOR
)
IS
BEGIN
    OPEN V_CURSOR FOR
        SELECT S.SUBJECT_NAME"과목명", SO.START_DATE"시작기간", SO.END_DATE"끝기간", T.TEXTBOOK_NAME"교재명"
         , SR.NAME"학생명", SI.ATTENDANCE_SCORE"출결", SI.WRITING_SCORE"필기", SI.PERFORMANCE_SCORE"실기"
         , SI.ATTENDANCE_SCORE*SO.ATTENDANCE_RATE*0.01"출결(배점적용)", SI.WRITING_SCORE*SO.WRITING_RATE*0.01"필기(배점적용)", SI.PERFORMANCE_SCORE*SO.PERFORMANCE_RATE*0.01"실기(배점적용)" 
         , SI.ATTENDANCE_SCORE*SO.ATTENDANCE_RATE*0.01 + SI.WRITING_SCORE*SO.WRITING_RATE*0.01 + SI.PERFORMANCE_SCORE*SO.PERFORMANCE_RATE*0.01 "총점"
         , RANK() OVER (PARTITION BY SI.OP_SUBJECT_CODE 
            ORDER BY (SI.ATTENDANCE_SCORE*SO.ATTENDANCE_RATE*0.01 
                      + SI.WRITING_SCORE*SO.WRITING_RATE*0.01 
                      + SI.PERFORMANCE_SCORE*SO.PERFORMANCE_RATE*0.01)) "등수"
         , CASE WHEN CR.REG_COURSE_CODE = SD.REG_COURSE_CODE THEN '중도탈락'
                ELSE ' ' END "중도탈락"
        FROM 
        (
            SELECT *
            FROM SUBJECT_OPEN
            WHERE OP_SUBJECT_CODE = (V_OP_SUBJECT_CODE)
        ) SO, TEXTBOOK T, SUBJECT S, SCORE_INPUT SI, COURSE_REGISTER CR, STUDENT_REGISTER SR, STUDENT_DROP SD
        WHERE SO.TEXTBOOK_CODE = T.TEXTBOOK_CODE
          AND SO.SUBJECT_CODE = S.SUBJECT_CODE
          AND SO.OP_SUBJECT_CODE = SI.OP_SUBJECT_CODE
          AND SI.REG_COURSE_CODE = CR.REG_COURSE_CODE
          AND SO.OP_COURSE_CODE = CR.OP_COURSE_CODE
          AND CR.STUDENT_CODE = SR.STUDENT_CODE
          AND CR.REG_COURSE_CODE = SD.REG_COURSE_CODE(+);
END;


-- *46
-- 학생 성적 삭제 프로시저
CREATE OR REPLACE PROCEDURE PRC_IN_SCR_DELETE
( V_SCORE_CODE           IN SCORE_INPUT.SCORE_CODE%TYPE 
)
IS
    V_SCORE_CODE_CHECK   SCORE_INPUT.SCORE_CODE%TYPE;
    USER_DEFINE_ERROR   EXCEPTION;
BEGIN
    SELECT SCORE_CODE INTO V_SCORE_CODE_CHECK
    FROM SCORE_INPUT
    WHERE SCORE_CODE = V_SCORE_CODE;
        
    DELETE
    FROM SCORE_INPUT
    WHERE SCORE_CODE = V_SCORE_CODE_CHECK;
    
    -- COMMIT
    COMMIT;
        
    EXCEPTION
        WHEN NO_DATA_FOUND
            THEN RAISE_APPLICATION_ERROR(-20500, '해당 성적이 존재하지 않습니다.');
                ROLLBACK;
        WHEN OTHERS
            THEN ROLLBACK;
END;


-- *47
--○ 성적 수정 프로시저
CREATE OR REPLACE PROCEDURE PRC_IN_SCR_UPDATE
( V_ATTENDANCE_SCORE     IN SCORE_INPUT.ATTENDANCE_SCORE%TYPE
, V_WRITING_SCORE        IN SCORE_INPUT.WRITING_SCORE%TYPE
, V_PERFORMANCE_SCORE    IN SCORE_INPUT.PERFORMANCE_SCORE%TYPE
, V_OP_SUBJECT_CODE     IN SUBJECT_OPEN.OP_SUBJECT_CODE%TYPE
, V_STUDENT_CODE     IN STUDENT_REGISTER.STUDENT_CODE%TYPE
)
IS
    V_OP_COURSE_CODE    COURSE_OPEN.OP_COURSE_CODE%TYPE;
    V_REG_COURSE_CODE   COURSE_REGISTER.REG_COURSE_CODE%TYPE;
    
    V_SCORE_CODE        SCORE_INPUT.SCORE_CODE%TYPE;
    
    USER_DEFINE_ERROR1   EXCEPTION;
    USER_DEFINE_ERROR2   EXCEPTION;
    USER_DEFINE_ERROR3   EXCEPTION;
BEGIN
    -- REG_COURSE_CODE 얻기 위한 과정 1
    SELECT OP_COURSE_CODE INTO V_OP_COURSE_CODE
    FROM SUBJECT_OPEN
    WHERE OP_SUBJECT_CODE = V_OP_SUBJECT_CODE;
    
    --REG_COURSE_CODE 얻기 위한 과정 2
    -- RIGHT OUTHER JOIN DUAL을 하는 이유
    -- ROW 조회결과가 없을 경우 NULL이 아니라 아예 없는 값
    -- 따라서 NULL 출력을 위해서 DUAL과 RIGHT OUTER JOIN을 함
    SELECT T.REG_COURSE_CODE INTO V_REG_COURSE_CODE
    FROM
    ( 
        SELECT REG_COURSE_CODE
        FROM COURSE_REGISTER
        WHERE STUDENT_CODE = V_STUDENT_CODE AND OP_COURSE_CODE = V_OP_COURSE_CODE
    ) T RIGHT OUTER JOIN DUAL
    ON 1=1;  
    
    IF (V_REG_COURSE_CODE IS NULL)
        THEN RAISE USER_DEFINE_ERROR3;
    END IF;
    
    -- 입력받은 학생이 해당 과목 성적이 있는지 없는지 유효성 검사
    
    -- SCORE_CODE를 받아오는데, 이게 비어있으면 학생의 과목 성적이 없는 것.
    
    SELECT T.SCORE_CODE INTO V_SCORE_CODE
    FROM
    (
        SELECT SCORE_CODE
        FROM SCORE_INPUT
        WHERE OP_SUBJECT_CODE = V_OP_SUBJECT_CODE
          AND REG_COURSE_CODE = V_REG_COURSE_CODE        
    ) T RIGHT OUTER JOIN DUAL
    ON 1=1;
       
    -- NULL 검사. 값없으면 에러.
    IF ( V_SCORE_CODE IS NULL )
        THEN RAISE USER_DEFINE_ERROR1;
    END IF;
    
    -- 0~100점 사이의 값인지 유효성 검사.
    -- 출결, 필기, 실기 0 ~ 100점 사이값인 경우만 UPDATE 진행하기
    -- 이외의 값은 예외발생
    IF ((V_ATTENDANCE_SCORE >= 0 AND V_ATTENDANCE_SCORE <= 100 )
        AND (V_WRITING_SCORE >= 0 AND V_WRITING_SCORE <= 100)
        AND (V_PERFORMANCE_SCORE >= 0 AND V_PERFORMANCE_SCORE <= 100))    
    THEN 
        UPDATE SCORE_INPUT
        SET ATTENDANCE_SCORE = V_ATTENDANCE_SCORE
          , WRITING_SCORE = V_WRITING_SCORE
          , PERFORMANCE_SCORE = V_PERFORMANCE_SCORE
        WHERE SCORE_CODE = V_SCORE_CODE;
    ELSE 
        RAISE USER_DEFINE_ERROR2;
    END IF;
    
        
    -- 예외 발생
    EXCEPTION
       WHEN USER_DEFINE_ERROR1
           THEN RAISE_APPLICATION_ERROR(-20500, '해당 성적이 존재하지 않습니다.');
               ROLLBACK;
       WHEN USER_DEFINE_ERROR2
           THEN RAISE_APPLICATION_ERROR(-20401, '점수는 0 ~ 100 사이의 값만 입력 가능합니다.');  
               ROLLBACK;
       WHEN USER_DEFINE_ERROR3
           THEN RAISE_APPLICATION_ERROR(-20701, '해당 학생의 수강신청 내역이 없습니다.');  
               ROLLBACK; 
       WHEN OTHERS
           THEN ROLLBACK;
    
    -- 커밋
    COMMIT;    
END;


-- *48
-- 입력하려는데, 값이 존재해서 수정해야하는 경우 쓰는 UPDATE 프로시저
CREATE OR REPLACE PROCEDURE PRC_IN_SCR_UPDATE2
( V_ATTENDANCE_SCORE     IN SCORE_INPUT.ATTENDANCE_SCORE%TYPE
, V_WRITING_SCORE        IN SCORE_INPUT.WRITING_SCORE%TYPE
, V_PERFORMANCE_SCORE    IN SCORE_INPUT.PERFORMANCE_SCORE%TYPE
, V_SCORE_CODE           IN SCORE_INPUT.SCORE_CODE%TYPE 
, V_REG_COURSE_CODE      IN COURSE_REGISTER.REG_COURSE_CODE%TYPE
)
IS
    USER_DEFINE_ERROR   EXCEPTION;
BEGIN
    -- 0~100점 사이의 값인지 유효성 검사.
    -- 출결, 필기, 실기 0 ~ 100점 사이값인 경우만 UPDATE 진행하기
    -- 이외의 값은 예외발생
    IF ((V_ATTENDANCE_SCORE >= 0 AND V_ATTENDANCE_SCORE <= 100 )
        AND (V_WRITING_SCORE >= 0 AND V_WRITING_SCORE <= 100)
        AND (V_PERFORMANCE_SCORE >= 0 AND V_PERFORMANCE_SCORE <= 100))    
        THEN UPDATE SCORE_INPUT
             SET ATTENDANCE_SCORE = V_ATTENDANCE_SCORE
               , WRITING_SCORE = V_WRITING_SCORE
               , PERFORMANCE_SCORE = V_PERFORMANCE_SCORE
             WHERE SCORE_CODE = V_SCORE_CODE;
    ELSE 
        RAISE USER_DEFINE_ERROR;
    END IF;

    -- 예외 발생
    EXCEPTION
       WHEN USER_DEFINE_ERROR
           THEN RAISE_APPLICATION_ERROR(-20401, '점수는 0 ~ 100 사이의 값만 입력 가능합니다.');  
               ROLLBACK;
       WHEN OTHERS
           THEN ROLLBACK;
    -- 커밋
    COMMIT;
END;


--------------------------------------------------------------------------------
-- *6
-- [학생]
--○ 학생 비밀번호변경 프로시저 PRC_STD_PW_CHANGE(ID,PW,NEWPW)
CREATE OR REPLACE PROCEDURE PRC_STD_PW_CHANGE
( V_STD_CODE  IN STUDENT_REGISTER.STUDENT_CODE%TYPE
, V_STD_PW    IN STUDENT_REGISTER.PASSWORD%TYPE
, V_STD_NEWPW IN STUDENT_REGISTER.PASSWORD%TYPE)
IS
    V_STD_PW2 STUDENT_REGISTER.PASSWORD%TYPE;
    USER_DEFINE_ERROR EXCEPTION;
BEGIN
    
    SELECT PASSWORD INTO V_STD_PW2
    FROM STUDENT_REGISTER
    WHERE STUDENT_CODE = V_STD_CODE;
    
    IF (V_STD_PW = V_STD_PW2)
        THEN UPDATE STUDENT_REGISTER
             SET PASSWORD = V_STD_NEWPW
             WHERE STUDENT_CODE = V_STD_CODE;
    ELSE
        RAISE USER_DEFINE_ERROR;
    END IF;
    
    -- 커밋
    COMMIT;
    
    EXCEPTION
       WHEN USER_DEFINE_ERROR
            THEN RAISE_APPLICATION_ERROR(-20103, '아이디, 비밀번호가 일치하지 않습니다.');
            ROLLBACK;
END;


-- *35
--○ 학생의 학생정보 수정 프로시저 PRC_STU_REG_STUEDIT
CREATE OR REPLACE PROCEDURE PRC_STU_REG_STUEDIT
(V_STD_COD       IN STUDENT_REGISTER.STUDENT_CODE%TYPE  --(학생코드)
,V_PW            IN STUDENT_REGISTER.PASSWORD%TYPE      --(비밀번호)
,V_NEW_PW        IN STUDENT_REGISTER.PASSWORD%TYPE      --(수정할 비밀번호)
,V_NAME          IN STUDENT_REGISTER.NAME%TYPE          --(학생명)
,V_SSN           IN STUDENT_REGISTER.SSN%TYPE           --(주민번호)
)
IS
    TEMP_STD_COD    NUMBER;
    TEMP_PW         NUMBER;
    
    STD_COD_ERROR   EXCEPTION;
    PW_ERROR        EXCEPTION;
BEGIN
    SELECT COUNT(*) INTO TEMP_STD_COD
      FROM STUDENT_REGISTER
     WHERE STUDENT_CODE = V_STD_COD;
     
    SELECT COUNT(*) INTO TEMP_PW
      FROM STUDENT_REGISTER
     WHERE STUDENT_CODE = V_STD_COD 
       AND PASSWORD = V_PW;
    
    IF(TEMP_STD_COD = 0)
        THEN RAISE STD_COD_ERROR;
    ELSIF (TEMP_PW = 0)
        THEN RAISE PW_ERROR;
    END IF;
    
    --UPDATE
    UPDATE STUDENT_REGISTER
      SET PASSWORD = V_NEW_PW,  NAME =  V_NAME  , SSN = V_SSN
    WHERE STUDENT_CODE = V_STD_COD
      AND PASSWORD = V_PW ;  
    
    EXCEPTION
        WHEN STD_COD_ERROR
            THEN RAISE_APPLICATION_ERROR(-20100, '해당 아이디가 존재하지 않습니다.');
                ROLLBACK;
         WHEN PW_ERROR
            THEN RAISE_APPLICATION_ERROR(-20103, '아이디, 비밀번호가 일치하지 않습니다.');
                ROLLBACK;
        WHEN OTHERS
            THEN ROLLBACK;
      
    COMMIT;
END;


-- *49
--○ 학생이 수강 끝낸 과목 리스트 확인하는 프로시저
CREATE OR REPLACE PROCEDURE PRC_GET_SUBJECT_LIST
( V_STUDENT_CODE    IN STUDENT_REGISTER.STUDENT_CODE%TYPE
, V_CURSOR          IN OUT SYS_REFCURSOR
)
IS
    V_REG_COURSE_CODE   COURSE_REGISTER.REG_COURSE_CODE%TYPE;
    
    STUDENT_EXIST       NUMBER;
    
    USER_DEFINE_ERROR1  EXCEPTION;
BEGIN
    SELECT COUNT(*) INTO STUDENT_EXIST
    FROM STUDENT_REGISTER
    WHERE STUDENT_CODE = V_STUDENT_CODE;
    
    IF (STUDENT_EXIST = 0)
        THEN RAISE USER_DEFINE_ERROR1;
    END IF;
    
    SELECT REG_COURSE_CODE INTO V_REG_COURSE_CODE
    FROM COURSE_REGISTER
    WHERE STUDENT_CODE = V_STUDENT_CODE;
    
    OPEN V_CURSOR FOR
        SELECT SO.OP_SUBJECT_CODE
        FROM
        (
            SELECT REG_COURSE_CODE, OP_COURSE_CODE, STUDENT_CODE
                 , CASE WHEN EXISTS ( SELECT 1
                                      FROM STUDENT_DROP
                                      WHERE REG_COURSE_CODE = V_REG_COURSE_CODE) -- 수강신청코드
                        THEN ( SELECT DROP_DATE
                               FROM STUDENT_DROP
                               WHERE REG_COURSE_CODE = V_REG_COURSE_CODE) -- 수강신청코드
                        ELSE SYSDATE END "CONDITION_DATE"
            FROM COURSE_REGISTER
            WHERE STUDENT_CODE = V_STUDENT_CODE -- 학생코드
        ) CR JOIN SUBJECT_OPEN SO ON CR.OP_COURSE_CODE = SO.OP_COURSE_CODE
        WHERE SO.END_DATE < CONDITION_DATE;
    
     EXCEPTION
        WHEN USER_DEFINE_ERROR1
            THEN RAISE_APPLICATION_ERROR(-20505, '학생이 존재하지 않습니다');
                ROLLBACK;
        WHEN NO_DATA_FOUND
            THEN RAISE_APPLICATION_ERROR(-20701, '해당 학생의 수강신청 내역이 없습니다.');
                ROLLBACK;
        WHEN OTHERS
            THEN ROLLBACK;
    
END;


-- *50
-- 학생의 한 과목 성적을 얻어오는 프로시저
CREATE OR REPLACE PROCEDURE PRC_GET_STUDENT_GRADE
( V_STUDENT_CODE    IN STUDENT_REGISTER.STUDENT_CODE%TYPE
, V_OP_SUBJECT_CODE IN SUBJECT_OPEN.OP_SUBJECT_CODE%TYPE
, V_CURSOR          OUT SYS_REFCURSOR
)
IS
    V_REG_COURSE_CODE       COURSE_REGISTER.REG_COURSE_CODE%TYPE;
    V_OP_COURSE_CODE        COURSE_REGISTER.OP_COURSE_CODE%TYPE;
    V_NAME                  STUDENT_REGISTER.NAME%TYPE;
    V_COURSE_NAME           COURSE.COURSE_NAME%TYPE;
BEGIN
    -- 수강신청코드, 과정개설코드
    SELECT REG_COURSE_CODE, OP_COURSE_CODE INTO V_REG_COURSE_CODE, V_OP_COURSE_CODE
    FROM COURSE_REGISTER
    WHERE STUDENT_CODE = V_STUDENT_CODE;
    
    -- 학생이름
    SELECT NAME INTO V_NAME
    FROM STUDENT_REGISTER
    WHERE STUDENT_CODE = V_STUDENT_CODE;
    
    -- 과정명
    SELECT C.COURSE_NAME INTO V_COURSE_NAME
    FROM COURSE_OPEN CO, COURSE C
    WHERE CO.COURSE_CODE = C.COURSE_CODE
      AND CO.OP_COURSE_CODE = V_OP_COURSE_CODE;
      
    OPEN V_CURSOR FOR
        SELECT V_NAME "학생명", V_COURSE_NAME "과정명", SI.SUBJECT_NAME "과목명", SI.START_DATE, SI.END_DATE
        , SI.TEXTBOOK_NAME "교재명", SI.ATTENDANCE_SCORE "출결점수", SI.WRITING_SCORE"필기점수", SI.PERFORMANCE_SCORE"실기점수"
        , SI.ATTENDENCE_SCORE_RATE"출결점수(배점)", SI.WRITING_SCORE_RATE"필기점수(배점)", SI.PERFORMANCE_SCORE_RATE"실기점수(배점)"
        , SI.TOTAL "총점", SI.RANK "등수"
        FROM
        (
            SELECT SI.REG_COURSE_CODE, S.SUBJECT_NAME, SO.START_DATE, SO.END_DATE, T.TEXTBOOK_NAME
                 , SI.ATTENDANCE_SCORE, SI.WRITING_SCORE, SI.PERFORMANCE_SCORE
                 , SI.ATTENDANCE_SCORE*SO.ATTENDANCE_RATE*0.01"ATTENDENCE_SCORE_RATE"
                 , SI.WRITING_SCORE*SO.WRITING_RATE*0.01"WRITING_SCORE_RATE"
                 , SI.PERFORMANCE_SCORE*SO.PERFORMANCE_RATE*0.01"PERFORMANCE_SCORE_RATE" 
                 , SI.ATTENDANCE_SCORE*SO.ATTENDANCE_RATE*0.01 
                    + SI.WRITING_SCORE*SO.WRITING_RATE*0.01 
                    + SI.PERFORMANCE_SCORE*SO.PERFORMANCE_RATE*0.01 "TOTAL"
                 , RANK() OVER (PARTITION BY SI.OP_SUBJECT_CODE
                    ORDER BY (SI.ATTENDANCE_SCORE*SO.ATTENDANCE_RATE*0.01 
                            + SI.WRITING_SCORE*SO.WRITING_RATE*0.01 
                            + SI.PERFORMANCE_SCORE*SO.PERFORMANCE_RATE*0.01)) "RANK"
            FROM
            (
                SELECT OP_SUBJECT_CODE, SUBJECT_CODE, TEXTBOOK_CODE, START_DATE, END_DATE
                     , ATTENDANCE_RATE, WRITING_RATE, PERFORMANCE_RATE
                FROM SUBJECT_OPEN
                WHERE OP_SUBJECT_CODE = V_OP_SUBJECT_CODE -- 입력받은 과목개설코드 
            ) SO JOIN TEXTBOOK T ON SO.TEXTBOOK_CODE = T.TEXTBOOK_CODE
                    JOIN SUBJECT S ON SO.SUBJECT_CODE = S.SUBJECT_CODE
                        JOIN SCORE_INPUT SI ON SO.OP_SUBJECT_CODE = SI.OP_SUBJECT_CODE
        ) SI
        WHERE SI.REG_COURSE_CODE = V_REG_COURSE_CODE;
END;


-- *51
--○ 학생이 자신이 수강하는 모든 과목에 대한 성적 출력 프로시저
CREATE OR REPLACE PROCEDURE PRC_PRINT_STUDENT_GRADE
( V_STUDENT_CODE    STUDENT_REGISTER.STUDENT_CODE%TYPE
)
IS
    -- 과목 리스트 받아옴
    V_OP_SUBJECT_CODE_LIST  SUBJECT_OPEN.OP_SUBJECT_CODE%TYPE;
    
    -- 과목리스트 받는 커서    
    V_CURSOR_SUBJECT_LIST   SYS_REFCURSOR;
    
    -- 학생 성적 받는 커서
    V_CURSOR_STUDENT_GRADE  SYS_REFCURSOR;
    
    V_NAME                      STUDENT_REGISTER.NAME%TYPE;
    V_COURSE_NAME               COURSE.COURSE_NAME%TYPE;
    V_SUBJECT_NAME              SUBJECT.SUBJECT_NAME%TYPE;
    V_START_DATE                SUBJECT_OPEN.START_DATE%TYPE;
    V_END_DATE                  SUBJECT_OPEN.END_DATE%TYPE;
    V_TEXTBOOK_NAME             TEXTBOOK.TEXTBOOK_NAME%TYPE;
    V_ATTENDANCE_SCORE          SCORE_INPUT.ATTENDANCE_SCORE%TYPE;
    V_WRITING_SCORE             SCORE_INPUT.WRITING_SCORE%TYPE;
    V_PERFORMANCE_SCORE         SCORE_INPUT.PERFORMANCE_SCORE%TYPE;
    V_ATTENDANCE_SCORE_RATE     NUMBER;
    V_WRITING_SCORE_RATE        NUMBER;
    V_PERFORMANCE_SCORE_RATE    NUMBER;
    V_TOTAL                     NUMBER;
    V_RANK                      NUMBER;
    
BEGIN
        
    PRC_GET_SUBJECT_LIST(V_STUDENT_CODE, V_CURSOR_SUBJECT_LIST);
    
    DBMS_OUTPUT.PUT_LINE('학생명' || CHR(9) || CHR(9) || '과정명' || CHR(9) || CHR(9) || '과목명' || '   ' || CHR(9)
                        || '시작일자' || '   ' || '종료일자' || '   ' || CHR(9) || '교재명' || '   ' ||  '출결점수'
                        || CHR(9) || '   ' || '필기점수' || CHR(9) || CHR(9) || '실기점수'
                        || CHR(9) || '   ' || '출결(배점)' || CHR(9)  
                        || '필기(배점)' || CHR(9) || '실기(배점)' 
                        || CHR(9) || '총점' || '    ' || '등수');
    
    LOOP
        FETCH V_CURSOR_SUBJECT_LIST INTO V_OP_SUBJECT_CODE_LIST;                
        EXIT WHEN V_CURSOR_SUBJECT_LIST%NOTFOUND;
        
        PRC_GET_STUDENT_GRADE( V_STUDENT_CODE, V_OP_SUBJECT_CODE_LIST, V_CURSOR_STUDENT_GRADE);
        LOOP
            FETCH V_CURSOR_STUDENT_GRADE INTO V_NAME, V_COURSE_NAME, V_SUBJECT_NAME, V_START_DATE, V_END_DATE
                                  , V_TEXTBOOK_NAME,  V_ATTENDANCE_SCORE, V_WRITING_SCORE, V_PERFORMANCE_SCORE
                                  , V_ATTENDANCE_SCORE_RATE, V_WRITING_SCORE_RATE, V_PERFORMANCE_SCORE_RATE
                                  , V_TOTAL, V_RANK;
                        
            
            EXIT WHEN V_CURSOR_STUDENT_GRADE%NOTFOUND;
            
            DBMS_OUTPUT.PUT_LINE(V_NAME || CHR(9) || CHR(9) || V_COURSE_NAME || CHR(9) || V_SUBJECT_NAME || '   ' 
                                || V_START_DATE || '   ' || V_END_DATE || '   ' || V_TEXTBOOK_NAME || '   ' ||  V_ATTENDANCE_SCORE
                                || CHR(9) || CHR(9) || '   ' || V_WRITING_SCORE || CHR(9) || CHR(9) || CHR(9) || V_PERFORMANCE_SCORE
                                || CHR(9) || CHR(9) || '   ' || V_ATTENDANCE_SCORE_RATE || CHR(9) || CHR(9) || '   ' 
                                || V_WRITING_SCORE_RATE || CHR(9) || CHR(9) || '   ' ||V_PERFORMANCE_SCORE_RATE 
                                || CHR(9) || CHR(9) || V_TOTAL || CHR(9) || CHR(9) || V_RANK);
        END LOOP;
        CLOSE V_CURSOR_STUDENT_GRADE;
    END LOOP;
    CLOSE V_CURSOR_SUBJECT_LIST;
END;

--------------------------------------------------------------------------------
--★뷰 생성 ★--

--------------------------------------------------------------------------------
-- *17
-- [과정관리]
--○ 관리자의 모든 과정 정보 출력 기능
-- 출력 정보 : 과정명, 강의실, 과목명, 기간, 교재명, 교수자명
CREATE OR REPLACE VIEW VIEW_MA_COU
AS
SELECT FN_COURSE(CO.COURSE_CODE) "과정명", FN_CLASSROOM_REGISTER(CO.CLASSROOM_CODE) "강의실"
     , FN_SUBJECT(SO.SUBJECT_CODE)"과목명"
     , CO.START_DATE "시작일자", CO.END_DATE "종료일자", CO.OPEN_DATE "개설일자"
     , FN_TEXTBOOK(SO.TEXTBOOK_CODE) "교재명"
     , FN_TEACHER_REGISTER(CO.TEACHER_CODE) "교수자명"
  FROM COURSE_OPEN CO JOIN SUBJECT_OPEN SO
    ON CO.OP_COURSE_CODE = SO.OP_COURSE_CODE;

-- *40
-- [중도탈락]
--○ 중도탈락학생 조회 VIEW
CREATE OR REPLACE VIEW VIEW_DROP_STUDENT_CK
AS
SELECT CR.REG_COURSE_CODE "수강신청코드", SR.NAME "학생명", SD.DROP_DATE "중도탈락일자"
     , CASE WHEN DROP_CODE IS NOT NULL THEN '중도탈락한 학생' ELSE '중도탈락하지 않은 학생' END "중도탈락여부"
     , DR.DETAIL "중도탈락사유"
FROM STUDENT_REGISTER SR, COURSE_REGISTER CR, STUDENT_DROP SD, DROP_REASON DR
WHERE SR.STUDENT_CODE = CR.STUDENT_CODE
  AND CR.REG_COURSE_CODE = SD.REG_COURSE_CODE
  AND SD.DR_REASON_CODE = DR.DR_REASON_CODE(+);
--------------------------------------------------------------------------------
SELECT *
FROM SCORE_INPUT;

--⑬
--○ 성적입력 테이블 데이터 입력
--   C1 세부과목 세 학생 정보
INSERT INTO SCORE_INPUT (SCORE_CODE, OP_SUBJECT_CODE, REG_COURSE_CODE, 
ATTENDANCE_SCORE, WRITING_SCORE, PERFORMANCE_SCORE)
VALUES ('OSC1_1', 'OSC1', 'CRC11', 70, 60, 50);
INSERT INTO SCORE_INPUT (SCORE_CODE, OP_SUBJECT_CODE, REG_COURSE_CODE, 
ATTENDANCE_SCORE, WRITING_SCORE, PERFORMANCE_SCORE)
VALUES ('OSC1_2', 'OSC1', 'CRC12', 20, 80, 50);
INSERT INTO SCORE_INPUT (SCORE_CODE, OP_SUBJECT_CODE, REG_COURSE_CODE, 
ATTENDANCE_SCORE, WRITING_SCORE, PERFORMANCE_SCORE)
VALUES ('OSC1_3', 'OSC1', 'CRC13', 90, 80, 90);

INSERT INTO SCORE_INPUT (SCORE_CODE, OP_SUBJECT_CODE, REG_COURSE_CODE, 
ATTENDANCE_SCORE, WRITING_SCORE, PERFORMANCE_SCORE)
VALUES ('OSC2_1', 'OSC2', 'CRC11', 20, 50, 50);
INSERT INTO SCORE_INPUT (SCORE_CODE, OP_SUBJECT_CODE, REG_COURSE_CODE, 
ATTENDANCE_SCORE, WRITING_SCORE, PERFORMANCE_SCORE)
VALUES ('OSC2_2', 'OSC2', 'CRC12', 50, 80, 50);
INSERT INTO SCORE_INPUT (SCORE_CODE, OP_SUBJECT_CODE, REG_COURSE_CODE, 
ATTENDANCE_SCORE, WRITING_SCORE, PERFORMANCE_SCORE)
VALUES ('OSC2_3', 'OSC2', 'CRC13', 60, 80, 90);

INSERT INTO SCORE_INPUT (SCORE_CODE, OP_SUBJECT_CODE, REG_COURSE_CODE, 
ATTENDANCE_SCORE, WRITING_SCORE, PERFORMANCE_SCORE)
VALUES ('OSC3_1', 'OSC3', 'CRC11', 70, 40, 50);
INSERT INTO SCORE_INPUT (SCORE_CODE, OP_SUBJECT_CODE, REG_COURSE_CODE, 
ATTENDANCE_SCORE, WRITING_SCORE, PERFORMANCE_SCORE)
VALUES ('OSC3_2', 'OSC3', 'CRC12', 20, 20, 50);
INSERT INTO SCORE_INPUT (SCORE_CODE, OP_SUBJECT_CODE, REG_COURSE_CODE, 
ATTENDANCE_SCORE, WRITING_SCORE, PERFORMANCE_SCORE)
VALUES ('OSC3_3', 'OSC3', 'CRC13', 90, 30, 90);

-- C2 세부과목 세 학생 세부 정보
INSERT INTO SCORE_INPUT (SCORE_CODE, OP_SUBJECT_CODE, REG_COURSE_CODE, 
ATTENDANCE_SCORE, WRITING_SCORE, PERFORMANCE_SCORE)
VALUES ('OSC4_1', 'OSC4', 'CRC21', 70, 60, 50);
INSERT INTO SCORE_INPUT (SCORE_CODE, OP_SUBJECT_CODE, REG_COURSE_CODE, 
ATTENDANCE_SCORE, WRITING_SCORE, PERFORMANCE_SCORE)
VALUES ('OSC4_2', 'OSC4', 'CRC22', 20, 80, 50);
INSERT INTO SCORE_INPUT (SCORE_CODE, OP_SUBJECT_CODE, REG_COURSE_CODE, 
ATTENDANCE_SCORE, WRITING_SCORE, PERFORMANCE_SCORE)
VALUES ('OSC4_3', 'OSC4', 'CRC23', 90, 80, 90);

INSERT INTO SCORE_INPUT (SCORE_CODE, OP_SUBJECT_CODE, REG_COURSE_CODE, 
ATTENDANCE_SCORE, WRITING_SCORE, PERFORMANCE_SCORE)
VALUES ('OSC5_1', 'OSC5', 'CRC21', 20, 50, 50);
INSERT INTO SCORE_INPUT (SCORE_CODE, OP_SUBJECT_CODE, REG_COURSE_CODE, 
ATTENDANCE_SCORE, WRITING_SCORE, PERFORMANCE_SCORE)
VALUES ('OSC5_2', 'OSC5', 'CRC22', 50, 80, 50);
INSERT INTO SCORE_INPUT (SCORE_CODE, OP_SUBJECT_CODE, REG_COURSE_CODE, 
ATTENDANCE_SCORE, WRITING_SCORE, PERFORMANCE_SCORE)
VALUES ('OSC5_3', 'OSC5', 'CRC23', 60, 80, 90);

INSERT INTO SCORE_INPUT (SCORE_CODE, OP_SUBJECT_CODE, REG_COURSE_CODE, 
ATTENDANCE_SCORE, WRITING_SCORE, PERFORMANCE_SCORE)
VALUES ('OSC6_1', 'OSC6', 'CRC21', 70, 40, 50);
INSERT INTO SCORE_INPUT (SCORE_CODE, OP_SUBJECT_CODE, REG_COURSE_CODE, 
ATTENDANCE_SCORE, WRITING_SCORE, PERFORMANCE_SCORE)
VALUES ('OSC6_2', 'OSC6', 'CRC22', 20, 20, 50);
INSERT INTO SCORE_INPUT (SCORE_CODE, OP_SUBJECT_CODE, REG_COURSE_CODE, 
ATTENDANCE_SCORE, WRITING_SCORE, PERFORMANCE_SCORE)
VALUES ('OSC6_3', 'OSC6', 'CRC23', 90, 30, 90);

-- C3 세부과목 C3S1. 세 학생 세부 정보
INSERT INTO SCORE_INPUT (SCORE_CODE, OP_SUBJECT_CODE, REG_COURSE_CODE, 
ATTENDANCE_SCORE, WRITING_SCORE, PERFORMANCE_SCORE)
VALUES ('OSC7_1', 'OSC7', 'CRC31', 70, 60, 50);
INSERT INTO SCORE_INPUT (SCORE_CODE, OP_SUBJECT_CODE, REG_COURSE_CODE, 
ATTENDANCE_SCORE, WRITING_SCORE, PERFORMANCE_SCORE)
VALUES ('OSC7_2', 'OSC7', 'CRC32', 20, 80, 50);
INSERT INTO SCORE_INPUT (SCORE_CODE, OP_SUBJECT_CODE, REG_COURSE_CODE, 
ATTENDANCE_SCORE, WRITING_SCORE, PERFORMANCE_SCORE)
VALUES ('OSC7_3', 'OSC7', 'CRC33', 90, 80, 90);
--------------------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE PRC_OP_COU_INSERT
(N_CODE      IN COURSE.COURSE_CODE%TYPE                     --과정코드
,N_SDATE    IN COURSE_OPEN.START_DATE%TYPE                  --시작날짜
,N_EDATE    IN COURSE_OPEN.END_DATE%TYPE                    --종료날짜
,N_CLACODE      IN CLASSROOM_REGISTER.CLASSROOM_CODE%TYPE     --강의실코드. 
)
IS
    V_OP_COURSE_CODE    COURSE_OPEN.OP_COURSE_CODE%TYPE;    -- 과정개설코드   C1 C2 C2...
BEGIN
    
    -- 과정개설코드 자동으로 부여
    SELECT NVL(MAX(TO_NUMBER(SUBSTR(OP_COURSE_CODE,2))),0) + 1 INTO V_OP_COURSE_CODE
    FROM COURSE_OPEN;
    
    V_OP_COURSE_CODE := 'C' || V_OP_COURSE_CODE;
    
    INSERT INTO COURSE_OPEN
    (OP_COURSE_CODE ,COURSE_CODE ,CLASSROOM_CODE ,START_DATE ,END_DATE) 
    VALUES(V_OP_COURSE_CODE,  N_CODE,N_CLACODE, TO_DATE(N_SDATE,'YYYY-MM-DD') ,TO_DATE(N_EDATE,'YYYY-MM-DD'));
    
END;
















